'use strict';
// =====================================================================
//  IDIOMA: português (original) ou inglês
//  Os textos do jogo estão escritos em português. Em inglês, cada texto
//  desenhado passa por traduzir(), que troca as frases conhecidas pela
//  tradução (das mais compridas para as mais curtas). Assim os nomes
//  compostos também se traduzem: "Espada Longa do Vampiro +3" ->
//  "Longsword of the Vampire +3". O resultado fica em cache.
// =====================================================================

let idioma = 'pt';
try { if (localStorage.getItem('masmorra_idioma') === 'en') idioma = 'en'; } catch (e) { /* sem storage */ }

const EN = {
  // ---------------- raridades e baús
  'Lixo': 'Junk', 'Comum': 'Common', 'Raro': 'Rare', 'Épico': 'Epic', 'Lendário': 'Legendary', 'Mítico': 'Mythic',
  'Baú de Madeira': 'Wooden Chest', 'Baú Amaldiçoado': 'Cursed Chest', 'Baú Dourado': 'Golden Chest',

  // ---------------- armas
  'Espada de Treino': 'Training Sword', 'Madeira pintada de cinzento.': 'Wood painted grey.',
  'Colher Enferrujada': 'Rusty Spoon', 'Oficialmente o PIOR item do jogo.': 'Officially the WORST item in the game.',
  'Galho Podre': 'Rotten Stick', 'Parte-se só de olhar para ele.': 'Breaks if you look at it.',
  'Peixe Morto': 'Dead Fish', 'Cheira muito mal.': 'Smells really bad.',
  'Adaga': 'Dagger', 'Rápida e leve.': 'Fast and light.',
  'Cajado de Aprendiz': 'Apprentice Staff', 'Cheira a livros velhos.': 'Smells like old books.',
  'Espada Curta': 'Short Sword', 'Fiável.': 'Reliable.',
  'Machadinha': 'Hatchet', 'Para lenha e monstros.': 'For firewood and monsters.',
  'Espada Longa': 'Longsword', 'Aço de qualidade.': 'Quality steel.',
  'Lança de Ferro': 'Iron Spear', 'Mantém-nos à distância.': 'Keeps them at a distance.',
  'Martelo de Guerra': 'War Hammer', 'Lento mas esmagador.': 'Slow but crushing.',
  'Cajado Arcano': 'Arcane Staff', 'Zumbe com energia.': 'Hums with energy.',
  'Lâmina Sombria': 'Shadow Blade', 'Sussurra no escuro.': 'Whispers in the dark.',
  'Machado Rúnico': 'Runic Axe', 'As runas brilham ao golpear.': 'The runes glow when it strikes.',
  'Cetro do Arquimago': 'Archmage Scepter', 'Os feitiços obedecem-lhe.': 'Spells obey it.',
  'Arrancada da pedra.': 'Pulled from the stone.',
  'Foice do Ceifador': 'Reaper\'s Scythe', 'Colhe almas.': 'Harvests souls.',
  'Espada do Infinito': 'Infinity Sword', 'O MELHOR item do jogo. Corta a própria realidade.': 'The BEST item in the game. Cuts reality itself.',
  // ---------------- armaduras
  'Saco de Batatas': 'Potato Sack', 'Pelo menos tapa.': 'At least it covers you.',
  'Cueca Furada': 'Holey Underpants', 'Deixa-te MAIS fraco. Parabéns.': 'Makes you WEAKER. Congrats.',
  'Balde na Cabeça': 'Bucket Helmet', 'Não se vê nada.': 'You can\'t see a thing.',
  'Túnica de Couro': 'Leather Tunic', 'Básica.': 'Basic.',
  'Cota de Malha': 'Chainmail', 'Faz barulho a andar.': 'Noisy when you walk.',
  'Armadura de Ferro': 'Iron Armor', 'Sólida.': 'Solid.',
  'Manto do Mago': 'Wizard Robe', 'Tecido encantado.': 'Enchanted cloth.',
  'Escamas de Dragão': 'Dragon Scales', 'Quente ao toque.': 'Warm to the touch.',
  'Manto Celestial': 'Celestial Mantle', 'Tecido pelas estrelas.': 'Woven by the stars.',
  'Armadura do Deus Antigo': 'Armor of the Old God', 'Nada te consegue tocar.': 'Nothing can touch you.',
  // ---------------- amuletos
  'Anel de Plástico': 'Plastic Ring', 'Saiu num ovo de chocolate.': 'Came in a chocolate egg.',
  'Pedra Qualquer': 'Random Rock', 'É só pesada.': 'It\'s just heavy.',
  'Anel de Cobre': 'Copper Ring', 'Um pouco de sorte.': 'A little luck.',
  'Pena Leve': 'Light Feather', 'Andas mais depressa.': 'You walk faster.',
  'Amuleto do Vampiro': 'Vampire Amulet', 'Cura-te ao causar dano.': 'Heals you when you deal damage.',
  'Anel da Força': 'Ring of Strength', 'Mais dano.': 'More damage.',
  'Anel do Vento': 'Wind Ring', 'Leve como o ar.': 'Light as air.',
  'Talismã Vital': 'Vital Talisman', 'Regenera vida.': 'Regenerates health.',
  'Amuleto de Safira': 'Sapphire Amulet', 'Guarda energia mágica.': 'Stores magic energy.',
  'Coração da Fénix': 'Phoenix Heart', 'Renasce das cinzas.': 'Rises from the ashes.',
  'Olho de Deus': 'Eye of God', 'Vê tudo. Pode tudo.': 'Sees all. Can do anything.',

  // ---------------- inimigos e bosses
  'Morcego': 'Bat', 'Esqueleto': 'Skeleton', 'Fantasma': 'Ghost', 'Zumbi': 'Zombie', 'Diabrete': 'Imp',
  'Slime de Lava': 'Lava Slime', 'Lobo de Gelo': 'Frost Wolf', 'Elemental de Gelo': 'Frost Elemental',
  'Rainha Aranha': 'Spider Queen', 'Aranha': 'Spider', 'Mímico': 'Mimic',
  'Rei Slime': 'Slime King', 'Lich Necromante': 'Necromancer Lich', 'Dragão Ancião': 'Ancient Dragon',
  'Golem de Pedra': 'Stone Golem', 'Rei Demónio': 'Demon King',
  // ---------------- elites
  'Veloz': 'Swift', '+50% velocidade': '+50% speed', 'Blindado': 'Armored', 'Recebe metade do dano': 'Takes half damage',
  'Explosivo': 'Explosive', 'Explode ao morrer': 'Explodes on death', 'Vampírico': 'Vampiric', 'Cura-se ao acertar-te': 'Heals when it hits you',
  // ---------------- salas
  'Loja do Mercador': 'Merchant\'s Shop', 'Gasta o teu ouro': 'Spend your gold',
  'Sala do Tesouro': 'Treasure Room', 'Guardada por um inimigo de elite': 'Guarded by an elite enemy',
  'Altar de Sacrifício': 'Sacrifice Altar', 'Troca vida por um Baú Dourado': 'Trade health for a Golden Chest',
  'Sala de Desafio': 'Challenge Room', 'Sobrevive a 3 ondas e ganha um Baú Dourado': 'Survive 3 waves and win a Golden Chest',
  'Sala de Encantamentos': 'Enchanting Room', 'Reforça e encanta o teu equipamento': 'Upgrade and enchant your gear',
  'Sala do Companheiro': 'Companion Room', 'Liberta um amigo para lutar contigo': 'Free a friend to fight by your side',
  // ---------------- afixos
  'de Fogo': 'of Fire', 'Queima os inimigos': 'Burns enemies', 'de Gelo': 'of Frost', 'Abranda os inimigos 40%': 'Slows enemies by 40%',
  'do Trovão': 'of Thunder', '25% de relâmpago em cadeia': '25% chain lightning', 'do Vampiro': 'of the Vampire',
  '+4% roubo de vida': '+4% life steal', 'da Fúria': 'of Fury', '+25% dano': '+25% damage', 'da Rapidez': 'of Haste',
  '+20% velocidade de ataque': '+20% attack speed', 'de Espinhos': 'of Thorns', 'Devolve 40% do dano recebido': 'Returns 40% of damage taken',
  'da Muralha': 'of the Wall', '+35% defesa': '+35% defense', 'da Vida': 'of Life', '+30% vida': '+30% health',
  'do Vento': 'of Wind', '+10% velocidade': '+10% speed', 'da Regeneração': 'of Regeneration', '+1.5 vida/s': '+1.5 health/s',
  'do Feiticeiro': 'of the Sorcerer', '+30 mana máxima': '+30 max mana', 'da Sorte': 'of Luck', 'Baús dão itens melhores': 'Chests give better items',
  'do Sábio': 'of the Sage', '+25% XP': '+25% XP', 'Arcano': 'Arcane', '+25% poder mágico': '+25% magic power',
  'da Crueldade': 'of Cruelty', '+10% crítico': '+10% crit', 'da Maldição': 'of the Curse', '-10% velocidade. Que azar.': '-10% speed. Bad luck.',
  // ---------------- melhorias
  'Força Bruta': 'Brute Force', '+15% de dano': '+15% damage', '+15% velocidade de ataque': '+15% attack speed',
  'Vitalidade': 'Vitality', '+30 vida máxima': '+30 max health', 'Pele de Pedra': 'Stone Skin', '+3 defesa': '+3 defense',
  'Olho Certeiro': 'Keen Eye', '+8% chance de crítico': '+8% crit chance', 'Pés Ligeiros': 'Light Feet', '+12% velocidade': '+12% speed',
  'Sanguessuga': 'Leech', '+3% roubo de vida': '+3% life steal', '+1.5 vida por segundo': '+1.5 health per second',
  'Sabedoria': 'Wisdom', '+20% de XP': '+20% XP', 'Trevo da Sorte': 'Lucky Clover', 'Esquiva Veloz': 'Quick Dodge',
  'Dash recarrega 25% mais rápido': 'Dash recharges 25% faster', 'Alquimista': 'Alchemist', '+2 poções e curam +15%': '+2 potions and they heal +15%',
  'Mente Arcana': 'Arcane Mind', '+20% poder mágico': '+20% magic power', 'Poço de Mana': 'Mana Well', '+25 mana máxima': '+25 max mana',
  'Canalizador': 'Channeler', '+2 mana por segundo': '+2 mana per second', 'Remoinho': 'Whirlwind',
  'Cada 4.º ataque atinge tudo à tua volta': 'Every 4th attack hits all around you', 'Lâminas Voadoras': 'Flying Blades',
  'Cada ataque lança uma lâmina (50% dano)': 'Each attack throws a blade (50% damage)', 'Escudo Divino': 'Divine Shield',
  'Bloqueia 1 golpe a cada 10 segundos': 'Blocks 1 hit every 10 seconds', 'Morte Explosiva': 'Explosive Death', 'Inimigos explodem ao morrer': 'Enemies explode on death',
  // ---------------- raças
  'Humano': 'Human', 'Versátil e com sorte.': 'Versatile and lucky.', '+20% XP': '+20% XP', '+1 poção ao começar': '+1 potion at start',
  'Começa com 40 ouro': 'Starts with 40 gold', 'Elfo': 'Elf', 'Rápido e nascido para a magia.': 'Fast and born for magic.',
  '+15% velocidade': '+15% speed', '+30% poder mágico': '+30% magic power', '+20 mana': '+20 mana', '-15 vida': '-15 health',
  'Anão': 'Dwarf', 'Duro como pedra e adora ouro.': 'Tough as stone and loves gold.', '+40 vida': '+40 health', '+4 defesa': '+4 defense',
  '+30% ouro': '+30% gold', '-10% velocidade': '-10% speed', 'Força bruta, pouca paciência para livros.': 'Brute strength, little patience for books.',
  '+20 vida': '+20 health', '-30% poder mágico': '-30% magic power', 'Vive do sangue dos inimigos.': 'Lives on the blood of enemies.',
  '+6% roubo de vida': '+6% life steal', '+1 sorte nos baús': '+1 chest luck', '-20 vida': '-20 health', 'Poções curam -15%': 'Potions heal -15%',
  // ---------------- skins
  'Cavaleiro Azul': 'Blue Knight', 'Carmesim': 'Crimson', 'Floresta': 'Forest', 'Sombra': 'Shadow', 'Real': 'Royal',
  'Dourado': 'Golden', 'Infinito': 'Infinity', 'Dracónica': 'Draconic',
  // ---------------- feitiços
  'Bola de Fogo': 'Fireball', 'Explode e queima os inimigos à volta': 'Explodes and burns nearby enemies',
  'Relâmpago': 'Lightning', 'Atinge o inimigo mais próximo e salta para outros': 'Hits the nearest enemy and jumps to others',
  'Nova de Gelo': 'Frost Nova', 'Fere e congela tudo à tua volta': 'Hurts and freezes everything around you',
  'Cura Divina': 'Divine Heal', 'Recupera muita vida': 'Restores a lot of health',
  // ---------------- dificuldade
  'Fácil': 'Easy', 'Inimigos mais fracos. Bom para aprender.': 'Weaker enemies. Good for learning.',
  'O jogo como foi pensado.': 'The game as intended.', 'Difícil': 'Hard',
  'Inimigos mais fortes e mais elites. Mais XP e ouro.': 'Stronger enemies and more elites. More XP and gold.',
  'Pesadelo': 'Nightmare', 'Só para os corajosos. Muito mais XP e ouro.': 'Only for the brave. Much more XP and gold.',
  // ---------------- zonas
  'Masmorra': 'Dungeon', 'Cemitério': 'Graveyard', 'Cavernas de Lava': 'Lava Caves', 'Abismo Gelado': 'Frozen Abyss', ' (Profundezas)': ' (Depths)',
  // ---------------- maldições
  'Frágil': 'Fragile', '-25% vida máxima': '-25% max health', 'Sangrento': 'Bleeding', 'Perdes 1 vida por segundo': 'Lose 1 health per second',
  'Pesado': 'Heavy', '-15% velocidade': '-15% speed', 'Avareza': 'Greed', '-40% ouro': '-40% gold', 'Vazio': 'Empty',
  '-30 mana máxima': '-30 max mana', 'Vulnerável': 'Vulnerable', 'Recebes +25% de dano': 'You take +25% damage',
  // ---------------- companheiros
  'Lobo': 'Wolf', 'Corre até aos inimigos e morde-os': 'Runs to enemies and bites them', 'Fada': 'Fairy',
  'Cura-te e dispara magia': 'Heals you and shoots magic', 'Mini-Dragão': 'Mini Dragon', 'Cospe bolas de fogo que explodem': 'Spits exploding fireballs',
  // ---------------- almas
  'Coração Forte': 'Strong Heart', '+10 vida máxima': '+10 max health', 'Braço de Ferro': 'Iron Arm', '+5% dano': '+5% damage',
  'Alma Arcana': 'Arcane Soul', '+10 mana máxima': '+10 max mana', 'Herança': 'Inheritance', 'Começa com +25 ouro': 'Start with +25 gold',
  'Bolsa de Poções': 'Potion Pouch', 'Memória Antiga': 'Ancient Memory', '+10% XP': '+10% XP', 'Estrela da Sorte': 'Lucky Star',
  'Aprendiz de Mago': 'Wizard\'s Apprentice', 'Começa a saber Relâmpago': 'Start knowing Lightning', 'Segunda Vida': 'Second Life',
  'Revives 1 vez por partida': 'Revive once per run',
  // ---------------- conquistas
  'Caçador de Reis': 'King Hunter', 'Derrota o Rei Slime': 'Defeat the Slime King', 'Explorador': 'Explorer', 'Aventureiro': 'Adventurer',
  'Tesouro Lendário': 'Legendary Treasure', 'Encontra um item Lendário': 'Find a Legendary item', 'Sorte Divina': 'Divine Luck',
  'Encontra um item Mítico': 'Find a Mythic item', 'Pesadelo Vivo': 'Living Nightmare', 'Mata o Dragão Ancião no Pesadelo': 'Kill the Ancient Dragon on Nightmare',
  'Fim do Demónio': 'End of the Demon', 'Derrota o Rei Demónio': 'Defeat the Demon King', 'Caçador de Mímicos': 'Mimic Hunter',
  'Mata 5 Mímicos (no total)': 'Kill 5 Mimics (in total)', 'Mestre Encantador': 'Master Enchanter', 'Reforça um item até +5': 'Upgrade an item to +5',
  'Arquimago': 'Archmage', 'Aprende os 4 feitiços numa partida': 'Learn all 4 spells in one run', 'Milionário': 'Millionaire',
  'Tem 1000 ouro ao mesmo tempo': 'Have 1000 gold at once', 'Amaldiçoado': 'Cursed', 'Equipa um item amaldiçoado': 'Equip a cursed item',
  'Melhor Amigo': 'Best Friend', 'Sobe o teu companheiro ao nível 5': 'Level your companion to 5', 'Colecionador': 'Collector',
  'Encontra 25 itens diferentes': 'Find 25 different items', 'Chega ao andar ': 'Reach floor ',

  // ---------------- interface
  'Armadura': 'Armor', 'Amuleto': 'Amulet', 'Arma': 'Weapon',
  'Dano: ': 'Damage: ', 'Velocidade: ': 'Speed: ', 'Alcance: ': 'Range: ', 'Crítico: ': 'Crit: ', 'Poder mágico: ': 'Magic power: ',
  'Defesa: ': 'Defense: ', 'Vida: ': 'Health: ', 'Roubo de vida: ': 'Life steal: ', 'Regeneração: ': 'Regeneration: ',
  'Não faz absolutamente nada.': 'Does absolutely nothing.', 'Nv ': 'Lv ', '[Q] Poção': '[Q] Potion', 'Equipado': 'Equipped',
  ' (por aprender)': ' (not learned)', ' (nível ': ' (level ', ' · Recarga ': ' · Cooldown ', 'Encontra um Livro de Feitiço': 'Find a Spellbook',
  '[C] Personagem': '[C] Character', '[I] Mochila': '[I] Bag', '[M] Som: ligado': '[M] Sound: on', '[M] Som: desligado': '[M] Sound: off',
  ' (Enfurecido)': ' (Enraged)', 'Usar: Descer': 'Use: Go down', '[E] Descer': '[E] Go down', 'Derrota o boss para abrir': 'Defeat the boss to open',
  'ANDAR ': 'FLOOR ', ' aplicada': ' applied', 'Todos os itens trazem': 'All items come with', 'uma maldição!': 'a curse!',
  'Usar: Abrir': 'Use: Open', '[E] Abrir': '[E] Open', 'Mercador': 'Merchant', '[E] Ver a loja': '[E] See the shop',
  'O altar já foi usado': 'The altar has been used', '[E] Sacrificar ': '[E] Sacrifice ', ' de vida': ' health',
  'e receber um Baú Dourado': 'and get a Golden Chest', ': Libertar ': ': Free ', 'Mesa de Encantamentos': 'Enchanting Table',
  '[E] Encantar equipamento': '[E] Enchant gear', '[E] Começar o desafio': '[E] Start the challenge',
  '3 ondas de inimigos · prémio: Baú Dourado': '3 waves of enemies · prize: Golden Chest', 'Onda ': 'Wave ',
  'Desafio concluído': 'Challenge complete', 'Maldição: ': 'Curse: ', 'A abrir: ': 'Opening: ',
  'Todos os itens deste baú trazem uma maldição!': 'Every item in this chest comes with a curse!',
  'Probabilidades': 'Odds', '[E] Saltar animação': '[E] Skip animation', 'Que azar... isto é LIXO!': 'Bad luck... this is JUNK!',
  'Épico!': 'Epic!', 'LENDÁRIO!': 'LEGENDARY!', 'MÍTICO!!! O MELHOR DO JOGO!': 'MYTHIC!!! THE BEST IN THE GAME!',
  'EQUIPADO AGORA': 'EQUIPPED NOW', 'Nada equipado': 'Nothing equipped', 'NOVO': 'NEW', '[E] Equipar': '[E] Equip', 'Equipar': 'Equip',
  'Mochila cheia': 'Bag full', 'Vender também dá +': 'Selling also gives +', ' · ao equipar, o item antigo vai para a mochila': ' · when you equip, the old item goes to your bag',
  'Vender +': 'Sell +', 'PERGAMINHO DE PODER': 'SCROLL OF POWER', 'SUBISTE DE NÍVEL!': 'LEVEL UP!', 'Escolhe uma melhoria': 'Choose an upgrade',
  'ÚNICA': 'UNIQUE', 'Carrega 1, 2 ou 3 (ou clica numa carta)': 'Press 1, 2 or 3 (or click a card)',
  '"Tudo tem um preço, aventureiro..."': '"Everything has a price, adventurer..."', 'ESGOTADO': 'SOLD OUT', 'À VENDA': 'FOR SALE',
  '% da vida e 40% da mana': '% health and 40% mana', '% da vida máxima': '% of max health', 'Sair': 'Exit',
  ' ou clique: comprar': ' or click: buy', 'E / Esc: sair': 'E / Esc: exit', 'PERSONAGEM': 'CHARACTER',
  'Poder mágico': 'Magic power', 'Ataques/segundo': 'Attacks/second', 'Roubo de vida': 'Life steal', 'Bónus de XP': 'XP bonus',
  'Sorte nos baús': 'Chest luck', 'Espinhos': 'Thorns', 'Cura das poções': 'Potion healing', 'Recarga do dash': 'Dash cooldown',
  ' (dano x2)': ' (damage x2)', ' dano)': ' damage)', 'Inimigos: ': 'Enemies: ', 'Baús: ': 'Chests: ', 'Tempo: ': 'Time: ',
  'Melhor item:': 'Best item:', 'Melhorias: ainda nenhuma. Sobe de nível!': 'Upgrades: none yet. Level up!', 'Melhorias': 'Upgrades',
  'Segunda Vida pronta': 'Second Life ready', 'C / Esc para voltar': 'C / Esc to go back',
  'Reforça um item (+1 até +5) ou dá-lhe um encantamento novo': 'Upgrade an item (+1 to +5) or give it a new enchantment',
  ': nada equipado': ': nothing equipped', 'Sem encantamento': 'No enchantment', '[E] Reforçar para +': '[E] Upgrade to +',
  'Reforço máximo (+5)': 'Max upgrade (+5)', 'Chance de sucesso: ': 'Success chance: ', 'Se falhar perdes o ouro': 'If it fails you lose the gold',
  '[R] Trocar o encantamento': '[R] Change the enchantment', '[R] Encantar (afixo aleatório)': '[R] Enchant (random affix)',
  'Ex.: de Fogo, do Trovão, de Espinhos, Arcano...': 'E.g.: of Fire, of Thunder, of Thorns, Arcane...',
  'ENCANTADO +': 'ENCHANTED +', 'Purificar (tira a maldição ': 'Purify (removes the curse ',
  '1-3: item  ·  E: reforçar  ·  R: encantar  ·  P: purificar  ·  Esc: sair': '1-3: item  ·  E: upgrade  ·  R: enchant  ·  P: purify  ·  Esc: exit',
  'CRIA A TUA PERSONAGEM': 'CREATE YOUR CHARACTER', '< Voltar': '< Back', 'Todas começam com a Bola de Fogo': 'Everyone starts with Fireball',
  'Conquista': 'Achievement', 'Dificuldade: ': 'Difficulty: ', 'Dificuldade ': 'Difficulty ', 'ENTER: Começar': 'ENTER: Start',
  'W/S: raça   A/D: skin   1-5: dificuldade   Esc: voltar': 'W/S: race   A/D: skin   1-5: difficulty   Esc: back',
  'MASMORRA DO DESTINO': 'DUNGEON OF DESTINY', 'Um RPG de masmorras, bosses e baús da sorte': 'A dungeon RPG of bosses and lucky chests',
  'Como jogar': 'How to play', 'Joystick (esquerda)': 'Joystick (left)', 'Mover': 'Move', 'Botão grande': 'Big button',
  'Atacar o inimigo mais perto': 'Attack the nearest enemy', 'Esquiva': 'Dodge', 'Abrir baús, lojas, escadas...': 'Open chests, shops, stairs...',
  'Beber poção': 'Drink potion', 'Feitiços (usam mana)': 'Spells (use mana)', 'Botões à direita': 'Buttons on the right',
  'Pausa, personagem, mochila': 'Pause, character, bag', 'WASD / Setas': 'WASD / Arrows', 'Clique / Espaço': 'Click / Space',
  'Atacar': 'Attack', 'Dash (esquiva)': 'Dash (dodge)', 'Abrir / Usar / Descer': 'Open / Use / Go down', 'Personagem / Mochila': 'Character / Bag',
  'Cada baú pode dar o PIOR ou o MELHOR item do jogo!': 'Every chest can give the WORST or the BEST item in the game!',
  'Recorde: Andar ': 'Record: Floor ', 'Almas: ': 'Souls: ', 'Coleção: ': 'Collection: ', 'Conquistas: ': 'Achievements: ',
  'ENTER: jogar · N: novo · A: almas · L: coleção · T: conquistas · I: idioma': 'ENTER: play · N: new · A: souls · L: collection · T: achievements · I: language',
  'PAUSA': 'PAUSED', 'Continuar (P)': 'Continue (P)', 'Guardar e sair (G)': 'Save and quit (G)', 'Desistir (X)': 'Give up (X)',
  'As tuas melhorias': 'Your upgrades', 'Ainda não tens melhorias. Sobe de nível!': 'No upgrades yet. Level up!',
  'O jogo guarda sozinho ao entrar em cada andar': 'The game saves automatically on every floor',
  'Desistir desta partida?': 'Give up this run?', 'A partida termina e a gravação é apagada.': 'The run ends and the save is deleted.',
  'O andar a que chegaste conta para o recorde.': 'The floor you reached counts for your record.', 'Sim, desistir (X)': 'Yes, give up (X)',
  'Não (Esc)': 'No (Esc)', 'DESISTISTE': 'YOU GAVE UP', 'MORRESTE': 'YOU DIED', 'Andar alcançado: ': 'Floor reached: ', 'Nível: ': 'Level: ',
  'Inimigos derrotados: ': 'Enemies defeated: ', 'Baús abertos: ': 'Chests opened: ', 'Melhor item encontrado:': 'Best item found:',
  'NOVO RECORDE!': 'NEW RECORD!', ' almas  (tens ': ' souls  (you have ', 'Gasta-as no Altar das Almas, no menu inicial': 'Spend them at the Soul Altar in the main menu',
  'Tentar outra vez': 'Try again', 'ENTER: Outra vez': 'ENTER: Again', 'Esc: Menu': 'Esc: Menu',
  'Roda o telemóvel': 'Rotate your phone', 'O jogo fica muito melhor na horizontal': 'The game is much better in landscape',
  'USAR': 'USE', 'Mochila (': 'Bag (', 'Na mochila (': 'In the bag (', 'NA MOCHILA': 'IN THE BAG', 'Mochila': 'Bag',
  'A mochila está vazia.': 'The bag is empty.', 'Quando abrires um baú, escolhe "Mochila" para guardar o item.': 'When you open a chest, choose "Bag" to keep the item.',
  '1-6: escolher  ·  E: equipar  ·  X: vender  ·  I / Esc: fechar': '1-6: choose  ·  E: equip  ·  X: sell  ·  I / Esc: close', 'Fechar': 'Close',
  'ALTAR DAS ALMAS': 'SOUL ALTAR', 'Tens ': 'You have ', ' almas  ·  Ganhas almas quando morres ou desistes (mais em dificuldades altas)': ' souls  ·  You earn souls when you die or give up (more on higher difficulties)',
  'As melhorias são permanentes e valem para todas as partidas novas': 'Upgrades are permanent and apply to every new run',
  'NÍVEL MÁXIMO': 'MAX LEVEL', 'Comprar: ': 'Buy: ', 'COLEÇÃO DE ITENS': 'ITEM COLLECTION', 'Encontraste ': 'You found ', ' itens': ' items',
  'Ainda não encontraste este item (': 'You haven\'t found this item yet (', 'Abre baús, compra na loja ou vence bosses para o descobrir.': 'Open chests, shop or beat bosses to discover it.',
  'Setas ou rato para ver cada item  ·  Esc: voltar': 'Arrows or mouse to see each item  ·  Esc: back', 'CONQUISTAS': 'ACHIEVEMENTS',
  ' desbloqueadas': ' unlocked', ' foi para a mochila': ' went to your bag', 'Mochila cheia: vendeste ': 'Bag full: you sold ',
  ' — BOSS': ' — BOSS', 'Nova zona: ': 'New zone: ', 'Cuidado... o próximo andar tem um BOSS!': 'Careful... the next floor has a BOSS!',
  'Encontra a escada para descer': 'Find the stairs to go down', 'Levanta-se...': 'Rising...', 'BOSS DERROTADO!': 'BOSS DEFEATED!',
  'Abre os baús e desce a escada': 'Open the chests and take the stairs', 'BLOQUEADO!': 'BLOCKED!', 'SEGUNDA VIDA!': 'SECOND LIFE!',
  'As almas trouxeram-te de volta': 'The souls brought you back', '+1 Poção': '+1 Potion', 'DESAFIO CONCLUÍDO!': 'CHALLENGE COMPLETE!',
  'Ganhaste um Baú Dourado': 'You won a Golden Chest', ' juntou-se a ti!': ' joined you!', 'Precisas de mais vida!': 'You need more health!',
  'ONDA ': 'WAVE ', 'Derrota todos os inimigos': 'Defeat all enemies', 'Poção de Vida': 'Health Potion', 'Cura parte da tua vida': 'Heals part of your health',
  'Cura Completa': 'Full Heal', 'Recupera toda a vida': 'Restores all health', 'Roda a roleta (nunca é Mímico)': 'Spin the wheel (never a Mimic)',
  'Roleta com as melhores chances': 'Wheel with the best odds', ' · equipa logo': ' · equips right away', 'Pergaminho de Poder': 'Scroll of Power',
  'Escolhe 1 de 3 melhorias': 'Choose 1 of 3 upgrades', 'Livro: ': 'Book: ', 'Sobe o feitiço para nível ': 'Raises the spell to level ',
  'Aprende um feitiço novo': 'Learn a new spell', 'Não tens ouro suficiente': 'Not enough gold', 'Já tens a vida cheia': 'Your health is already full',
  'Vida recuperada': 'Health restored', 'Equipaste ': 'You equipped ', ': nível ': ': level ', ' ENFURECEU-SE!': ' IS ENRAGED!', 'Fase 2': 'Phase 2',
  'PRESO NA TEIA!': 'STUCK IN THE WEB!', 'Ainda não sabes este feitiço': 'You don\'t know this spell yet', 'Sem mana!': 'No mana!',
  'Nenhum inimigo à vista': 'No enemy in sight', 'Já dominas ': 'You already mastered ', ' nível ': ' level ', 'Aprendeste: ': 'You learned: ',
  'O feitiço ficou mais forte': 'The spell got stronger', 'Carrega ': 'Press ', ' para lançar': ' to cast', 'Novo feitiço!': 'New spell!',
  'Este item já está no máximo (+5)': 'This item is already maxed (+5)', 'Sucesso! ': 'Success! ', 'O encantamento falhou... perdeste o ouro.': 'The enchantment failed... you lost the gold.',
  'Novo encantamento: ': 'New enchantment: ', 'A maldição foi quebrada!': 'The curse is broken!', 'Vendeste ': 'You sold ', ' por ': ' for ',
  'Continuar': 'Continue', 'Novo jogo': 'New game', 'Começar': 'Start', 'Altar das Almas (': 'Soul Altar (', 'Coleção de itens': 'Item collection',
  'Conquistas': 'Achievements', 'Desbloqueia com a conquista ': 'Unlock with the achievement ', ' para desbloquear esta skin': ' to unlock this skin',
  'É UM MÍMICO!': 'IT\'S A MIMIC!', 'Guardado na mochila': 'Stored in your bag', 'Nova skin desbloqueada: ': 'New skin unlocked: ',
  'Conquista: ': 'Achievement: ', ' subiu para nível ': ' went up to level ', 'Não tens almas suficientes. Joga mais partidas!': 'Not enough souls. Play more runs!',
  'Já está no nível máximo': 'Already at max level', 'Personagem': 'Character', 'Pausa': 'Pause', 'Poção': 'Potion', 'Usar': 'Use',
  'Vida': 'Health', 'Dano': 'Damage', 'Crítico': 'Crit', 'Alcance': 'Range', 'Defesa': 'Defense', 'Velocidade': 'Speed', 'Regeneração': 'Regeneration',
  'Nível ': 'Level ', 'Andar ': 'Floor ', ' ouro': ' gold', ' almas': ' souls', 'Skin ': 'Skin ', 'Menu': 'Menu', 'SUBIU DE NÍVEL!': 'LEVEL UP!',
  'Vampiro': 'Vampire', 'Gelo': 'Ice', 'Fúria': 'Fury', 'Cura ': 'Heals ', 'Sorte +': 'Luck +', ' de ': ' of ',
  'ARMADURA': 'ARMOR', 'ARMA': 'WEAPON', 'AMULETO': 'AMULET',
  // caçadores jogáveis e portais
  'Do Vazio': 'Void', 'Som: desligado': 'Sound: off', 'Som: ligado': 'Sound: on', 'Sound: desligado': 'Sound: off', 'Sound: ligado': 'Sound: on',
  'Derrota todos os monstros': 'Defeat all the monsters',
  'Caçador das Sombras': 'Shadow Hunter', 'Troca de Sombra': 'Shadow Exchange', 'TROCA DE SOMBRA': 'SHADOW EXCHANGE',
  'Trocas de lugar com a tua sombra mais longe e o exército fica +50% mais forte': 'Swap places with your farthest shadow and your army gets +50% stronger',
  '"Ergue-te!" desde o nível 1 e +2 sombras': '"Arise!" from level 1 and +2 shadows',
  'Dançarina da Espada': 'Sword Dancer', 'Dança da Espada': 'Sword Dance',
  'Atravessa os monstros num relâmpago e corta todos pelo caminho (dano x3)': 'Flash through the monsters and cut everyone in your path (x3 damage)',
  '+15% vel. de ataque e +5% crítico': '+15% attack speed and +5% crit',
  'Imperador das Chamas': 'Flame Emperor', 'Chuva de Meteoros': 'Meteor Shower', 'CHUVA DE METEOROS': 'METEOR SHOWER',
  'Faz cair meteoros de fogo à volta do alvo': 'Rains fire meteors around the target', '+40% poder mágico e Bola de Fogo nível 2': '+40% magic power and Fireball level 2',
  'Tigre Branco': 'White Tiger', 'Forma Bestial': 'Beast Form', 'FORMA BESTIAL': 'BEAST FORM',
  'Transformas-te em fera durante 8 s: +50% dano, +30% velocidade e roubo de vida': 'Turn into a beast for 8 s: +50% damage, +30% speed and life steal',
  '+40 vida': '+40 health', 'Colosso': 'Colossus', 'Punho do Titã': "Titan's Fist",
  'Esmaga o chão: atordoa tudo à volta e levas -50% dano durante 4 s': 'Smash the ground: stuns everything around and you take -50% damage for 4 s',
  '+60 vida e +6 defesa, -10% velocidade': '+60 health and +6 defense, -10% speed',
  'Curandeiro Supremo': 'Supreme Healer', 'Luz Sagrada': 'Holy Light',
  'Cura 30% da vida, tira o veneno e queima os monstros à volta (x2 em mortos-vivos)': 'Heals 30% health, removes poison and burns nearby monsters (x2 vs undead)',
  '+2 vida por segundo e poções +15%': '+2 health per second and potions +15%',
  'Mestre das Lâminas': 'Blade Master', 'Corte do Vento': 'Wind Slash', 'Lança um leque de lâminas de vento que atravessam os monstros': 'Throws a fan of wind blades that pierce monsters',
  '+15% velocidade': '+15% speed', 'Aventureiro': 'Adventurer', 'Sem habilidade especial': 'No special skill', 'Sem habilidade': 'No skill', '+10% XP': '+10% XP',
  'Não tens sombras': 'You have no shadows', 'Paralisado!': 'Paralyzed!', 'Caçador: ': 'Hunter: ', 'Caçador': 'Hunter', 'Raça': 'Race',
  'Tab: caçador/raça   W/S: escolher   A/D: skin   1-5: dificuldade   Esc: voltar': 'Tab: hunter/race   W/S: choose   A/D: skin   1-5: difficulty   Esc: back',
  'Escolhe um caçador, uma raça, uma skin e a dificuldade': 'Pick a hunter, a race, a skin and the difficulty',
  'Presa Venenosa': 'Venom Fang', 'Paralisa às vezes os monstros.': 'Sometimes paralyzes monsters.', 'Espada Celeste': 'Celestial Sword', 'Leve como uma pena.': 'Light as a feather.',
  'Cajado Flamejante': 'Flaming Staff', 'Nunca arrefece.': 'Never cools down.', 'Garras de Tigre': 'Tiger Claws', 'Rasgam como as de um tigre branco.': 'They tear like a white tiger\'s.',
  'Manoplas do Titã': 'Titan Gauntlets', 'Cada murro abana o chão.': 'Every punch shakes the ground.', 'Bastão Sagrado': 'Holy Rod', 'Brilha perto dos mortos-vivos.': 'Glows near the undead.',
  'Espadas Gémeas do Vento': 'Twin Wind Swords', 'Cortam o ar a assobiar.': 'They whistle as they cut the air.',
  'Mata-Cavaleiros': 'Knight Slayer', 'Comprada numa loja que ninguém mais vê.': 'Bought in a shop no one else can see.',
  'Fúria do Dragão': "Dragon's Fury", 'Feitas com os dentes de um dragão rei.': 'Made from the teeth of a dragon king.',
  'Adagas do Rei Demónio': "Demon King's Daggers", 'O rei dos demónios ainda as quer de volta.': 'The demon king still wants them back.',
  'Orbe da Ganância': 'Orb of Greed', 'Duplica o poder dos teus feitiços.': 'Doubles the power of your spells.',
  'PORTAL VERMELHO! Não há saída até matares o boss': 'RED GATE! No way out until you kill the boss', 'Derrota as ondas e o boss do portal': 'Defeat the waves and the gate boss',
  'PORTAL RANK ': 'GATE RANK ', 'BOSS DO PORTAL ': 'GATE BOSS ', 'PORTAL VERMELHO': 'RED GATE', ' CONQUISTADO!': ' CLEARED!', 'PORTAL ': 'GATE ',
  ' · abre os baús e sai pelo portal': ' · open the chests and leave through the gate', 'Voltaste à masmorra': 'You are back in the dungeon',
  ': Sair do portal': ': Leave the gate', ': Entrar': ': Enter', 'MUITO PERIGOSO': 'VERY DANGEROUS', 'Perigoso': 'Dangerous', 'Fácil': 'Easy',
  ' · monstros x': ' · monsters x', ' · boss: ': ' · boss: ', 'Portal Rank ': 'Gate Rank ', 'Portal ': 'Gate ',
  'Portal S': 'S Gate', 'Conquista um Portal de Rank S ou maior': 'Clear a Rank S gate or higher', 'Além do Limite': 'Beyond the Limit',
  'Conquista um Portal de Rank SSS': 'Clear a Rank SSS gate', 'Portal Vermelho': 'Red Gate', 'Sobrevive a um Portal Vermelho': 'Survive a Red Gate',
  // caçador: atributos, habilidades, sombras, poder e rank
  'ESTADO': 'STATUS', 'Estado (U)': 'Status (U)', 'Estado (+': 'Status (+', 'RANK': 'RANK', 'Rank ': 'Rank ',
  'Poder de combate: ': 'Combat power: ', 'PODER ': 'POWER ', 'Portal Rank ': 'Gate Rank ', ' · recomendado ': ' · recommended ',
  ' · poder recomendado ': ' · recommended power ', ' · o teu: ': ' · yours: ',
  'Muito mais forte do que este portal. Os monstros também ficaram mais fortes.': 'Much stronger than this gate. The monsters got stronger too.',
  'Mais forte do que este portal.': 'Stronger than this gate.', 'Ao nível deste portal. Cuidado.': 'On par with this gate. Careful.',
  'Mais fraco do que este portal. Perigo!': 'Weaker than this gate. Danger!',
  'Equilíbrio: monstros +': 'Balance: monsters +', '% vida, +': '% health, +', '% dano': '% damage',
  'ATRIBUTOS': 'ATTRIBUTES', 'Pontos: ': 'Points: ', 'Força': 'Strength', 'Agilidade': 'Agility', 'Vitalidade': 'Vitality',
  'Inteligência': 'Intelligence', 'Perceção': 'Perception', '+1% dano': '+1% damage', '+0.8% vel. de ataque e +0.3% vel.': '+0.8% attack speed and +0.3% speed',
  '+1.5% vida máxima': '+1.5% max health', '+2% poder mágico e +1 mana': '+2% magic power and +1 mana', '+0.4% crítico': '+0.4% crit',
  'Ganhas 2 pontos em cada nível': 'You get 2 points every level', 'HABILIDADES DE CAÇADOR': 'HUNTER SKILLS',
  'Ergue-te!': 'Arise!', 'ERGUE-TE!': 'ARISE!', 'Sede de Sangue': 'Bloodlust', 'SEDE DE SANGUE': 'BLOODLUST', 'Mão Invisível': 'Invisible Hand', 'Furtividade': 'Stealth',
  'Os monstros que mataste há pouco levantam-se como soldados sombra': 'Monsters you just killed rise as shadow soldiers',
  'Os monstros à tua volta ficam paralisados de medo e levam +30% dano': 'Monsters around you freeze in fear and take +30% damage',
  'Uma força invisível esmaga e empurra os monstros à tua frente': 'An invisible force crushes and pushes the monsters in front of you',
  'Ficas invisível 5 s e o golpe seguinte faz dano x3': 'You turn invisible for 5 s and your next hit deals x3 damage',
  'EXÉRCITO DAS SOMBRAS': 'SHADOW ARMY', ' soldados': ' soldiers', ' + 1 boss': ' + 1 boss', 'Desbloqueia no nível 5': 'Unlocks at level 5',
  'Mata monstros e usa "Ergue-te!" (tecla 5) perto dos corpos': 'Kill monsters and use "Arise!" (key 5) near the bodies',
  'Toca fora dos botões para voltar': 'Tap outside the buttons to go back', 'U / Esc para voltar': 'U / Esc to go back',
  'Não há corpos perto': 'No bodies nearby', 'Exército cheio (': 'Army full (', 'Desbloqueia no nível ': 'Unlocks at level ',
  'EMBOSCADA!': 'AMBUSH!', '[Sistema] Nova habilidade: ': '[System] New skill: ', '[Sistema] Tens pontos de atributo': '[System] You have attribute points',
  'Abre a Janela de Estado (': 'Open the Status Window (', 'botão do herói': 'hero button', 'tecla U': 'key U', ') para os usar': ') to spend them',
  'Tecla ': 'Key ', 'Mana ': 'Mana ', ' · Recarga ': ' · Cooldown ', ' · tecla ': ' · key ', ' (nível ': ' (level ',
  '[C] Personagem   [U] Estado   [I] Mochila   [M] Som: ': '[C] Character   [U] Status   [I] Bag   [M] Sound: ',
  'Rei das Sombras': 'Shadow King', 'Tem 10 sombras no teu exército': 'Have 10 shadows in your army',
  'Caçador de Rank S': 'Rank S Hunter', 'Chega ao Rank S': 'Reach Rank S', 'Nível Nacional': 'National Level', 'Chega ao Rank Nacional': 'Reach National Rank',
  'Nacional': 'National',
  // pacto, missões, estatísticas, salas secretas, Diabo e Anjo, bestiário
  'PACTO DE CASTIGO': 'PACT OF PUNISHMENT', 'Pacto de Castigo (Calor ': 'Pact of Punishment (Heat ', 'Pacto de Castigo': 'Pact of Punishment',
  'Escolhe regras mais difíceis para as próximas partidas. Cada ponto de Calor dá +10% almas.': 'Pick harder rules for your next runs. Each point of Heat gives +10% souls.',
  'Calor ': 'Heat ', ' calor': ' heat', 'almas x': 'souls x', 'Desligado': 'Off',
  'Força Bruta': 'Brute Force', 'Os monstros fazem +20% dano (por nível)': 'Monsters deal +20% damage (per level)',
  'Pele de Pedra': 'Stone Skin', 'Os monstros têm +25% vida (por nível)': 'Monsters have +25% health (per level)',
  'Enxame': 'Swarm', '+25% monstros em cada andar (por nível)': '+25% monsters on every floor (per level)',
  'Elite': 'Elite', '+60% de monstros de elite (por nível)': '+60% elite monsters (per level)',
  'Pressa': 'Haste', 'Os monstros são 12% mais rápidos (por nível)': 'Monsters are 12% faster (per level)',
  'Secura': 'Drought', 'As poções curam -25% (por nível)': 'Potions heal -25% (per level)',
  'Pobreza': 'Poverty', 'Ganhas -30% ouro': 'You earn -30% gold',
  'Campeões': 'Champions', 'Muitos mais Veteranos e Campeões (por nível)': 'Many more Veterans and Champions (per level)',
  'Bosses Furiosos': 'Furious Bosses', 'Os bosses têm +30% vida e enfurecem-se mais cedo': 'Bosses have +30% health and enrage sooner',
  'Toca numa regra para subir o nível (volta a 0 no fim)': 'Tap a rule to raise its level (goes back to 0 at the end)',
  'Clica ou carrega 1-9 para subir o nível · 0 desliga tudo · Esc: voltar': 'Click or press 1-9 to raise the level · 0 turns all off · Esc: back',
  'MISSÕES E ESTATÍSTICAS': 'MISSIONS AND STATS', 'Missões e estatísticas': 'Missions and stats', 'Missões de hoje': "Today's missions",
  'Há missões novas todos os dias': 'There are new missions every day', 'Feita!': 'Done!', 'Missão cumprida!': 'Mission complete!',
  'Mata {n} monstros de elite': 'Kill {n} elite monsters', 'Mata {n} monstros': 'Kill {n} monsters', 'Abre {n} baús': 'Open {n} chests',
  'Chega ao andar {n}': 'Reach floor {n}', 'Derrota {n} bosses': 'Defeat {n} bosses', 'Apanha {n} de ouro': 'Collect {n} gold',
  'Lança {n} feitiços': 'Cast {n} spells', 'Mata {n} Campeões': 'Kill {n} Champions', 'Apanha {n} relíquias': 'Collect {n} relics',
  'Bebe {n} poções': 'Drink {n} potions', 'Encontra {n} salas secretas': 'Find {n} secret rooms',
  'Estatísticas': 'Statistics', 'Partidas': 'Runs', 'Mortes': 'Deaths', 'Tempo de jogo': 'Play time', 'Andar mais fundo': 'Deepest floor',
  'Monstros mortos': 'Monsters killed', 'Bosses derrotados': 'Bosses defeated', 'Baús abertos': 'Chests opened', 'Ouro apanhado': 'Gold collected',
  'Relíquias apanhadas': 'Relics collected', 'Salas secretas': 'Secret rooms', 'Feitiços lançados': 'Spells cast', 'Pactos com o Diabo': 'Deals with the Devil',
  'Últimas partidas': 'Latest runs', 'Ainda não acabaste nenhuma partida': "You haven't finished a run yet", 'Desistiu': 'Gave up',
  'Morto por: ': 'Killed by: ', 'uma armadilha': 'a trap', 'o fogo no chão': 'the fire on the ground',
  'SALA SECRETA!': 'SECRET ROOM!', 'Encontraste um esconderijo': 'You found a hideout',
  'Sala do Diabo': 'Devil Room', 'Troca vida máxima por poder': 'Trade max health for power', 'Sala do Anjo': 'Angel Room',
  'Escolhe um presente. Só um!': 'Pick one gift. Only one!', 'O Diabo sorri...': 'The Devil smiles...', 'O Anjo observa-te': 'The Angel watches you',
  'Escolhe só um dos presentes': 'Pick only one of the gifts', 'Já não tens vida para vender!': 'You have no health left to sell!',
  '% vida máxima': '% max health', ': Pagar ': ': Pay ', '% da vida máxima': '% of max health', ': Levar (os outros desaparecem)': ': Take (the others vanish)',
  'COLEÇÃO': 'COLLECTION', 'Coleção e Bestiário': 'Collection and Bestiary', 'Itens ': 'Items ', 'Monstros ': 'Monsters ', 'Relíquias ': 'Relics ',
  'Zonas: ': 'Zones: ', 'Veterano: ': 'Veteran: ', 'Campeão: ': 'Champion: ', 'Ainda não encontraste este monstro.': "You haven't found this monster yet.",
  'Ainda não encontraste esta relíquia.': "You haven't found this relic yet.",
  'Aparecem nos bosses, Baús Dourados, Sala de Desafio e loja,': 'They drop from bosses, Golden Chests, the Challenge Room and the shop,',
  'nas salas secretas e nas salas do Diabo e do Anjo.': 'secret rooms and the Devil and Angel rooms.',
  'Salta para cima de ti.': 'Jumps on you.', 'Voa aos ziguezagues.': 'Flies in zigzags.', 'Dispara flechas quando te vê.': 'Shoots arrows when it sees you.',
  'Prepara-se e faz uma investida.': 'Winds up and charges.', 'Atravessa paredes.': 'Goes through walls.', 'Levanta-se uma vez depois de morrer.': 'Gets back up once after dying.',
  'Atira bolas de fogo.': 'Throws fireballs.', 'Explode quando morre.': 'Explodes when it dies.', 'Muito rápido. A mordida abranda-te.': 'Very fast. Its bite slows you.',
  'Dispara três pedaços de gelo.': 'Shoots three shards of ice.', 'Pequena, rápida e aos ziguezagues.': 'Small, fast and zigzagging.', 'Finge ser um baú.': 'Pretends to be a chest.',
  'Boss do andar ': 'Boss of floor ',
  'Aquecimento': 'Warming Up', 'Começa uma partida com Calor 5': 'Start a run with Heat 5', 'Em Chamas': 'On Fire', 'Começa uma partida com Calor 10': 'Start a run with Heat 10',
  'Caça-Segredos': 'Secret Hunter', 'Encontra 3 salas secretas (no total)': 'Find 3 secret rooms (in total)',
  'Pacto com o Diabo': 'Deal with the Devil', 'Faz 3 negócios com o Diabo (no total)': 'Make 3 deals with the Devil (in total)',
  'Trabalhador': 'Hard Worker', 'Cumpre 10 missões diárias': 'Complete 10 daily missions',
  'ENTER: jogar · N: novo · A: almas · K: pacto · L: coleção · T: conquistas · R: missões · I: idioma': 'ENTER: play · N: new · A: souls · K: pact · L: collection · T: achievements · R: missions · I: language',
  // armas novas e tipos de arma
  'Fisga de Borracha': 'Rubber Slingshot', 'Um brinquedo. Quase inútil.': 'A toy. Almost useless.',
  'Arco Curto': 'Short Bow', 'Dispara flechas de longe.': 'Shoots arrows from afar.',
  'Adagas Gémeas': 'Twin Daggers', 'Duas lâminas, o dobro da pressa.': 'Two blades, twice the hurry.',
  'Arco Longo': 'Longbow', 'Alcança o outro lado da sala.': 'Reaches the other side of the room.',
  'Katana': 'Katana', 'Corta o vento.': 'Cuts the wind.',
  'Foice de Camponês': "Farmer's Scythe", 'Ceifa trigo e esqueletos.': 'Reaps wheat and skeletons.',
  'Arco Élfico': 'Elven Bow', 'Feito de madeira de árvore da lua.': 'Made from moon tree wood.',
  'Martelo do Trovão': 'Thunder Hammer', 'Cada pancada ecoa como trovão.': 'Every blow echoes like thunder.',
  'Lança do Dragão': 'Dragon Lance', 'Forjada com uma escama de dragão.': 'Forged with a dragon scale.',
  'Arco das Estrelas': 'Star Bow', 'As flechas brilham como cometas.': 'The arrows shine like comets.',
  'Tridente do Mar': 'Sea Trident', 'Roubado a um deus do oceano.': 'Stolen from an ocean god.',
  'Adagas da Sombra': 'Shadow Daggers', 'Nunca as vês chegar.': 'You never see them coming.',
  'Arco do Fim do Mundo': 'Bow of the World\'s End', 'Cada flecha é uma estrela cadente.': 'Every arrow is a shooting star.',
  'Tipo: ': 'Type: ', 'Espada': 'Sword', 'Machado': 'Axe', 'Lança': 'Spear', 'Martelo': 'Hammer', 'Foice': 'Scythe', 'Cajado': 'Staff', 'Arco': 'Bow',
  'Golpe em arco à tua frente': 'Arc swing in front of you', 'Muito rápida; os críticos fazem dano x2.5': 'Very fast; crits deal x2.5 damage',
  'Golpe largo que empurra os inimigos para longe': 'Wide swing that knocks enemies far away',
  'Estocada comprida que atravessa todos em linha': 'Long thrust that pierces everyone in a line',
  'Esmaga tudo à tua volta e abranda os inimigos': 'Smashes everything around you and slows enemies',
  'Varre quase tudo à tua volta e rouba vida': 'Sweeps almost everything around you and steals life',
  'Golpe e também dispara uma bola de magia': 'Swings and also fires a magic bolt',
  'Dispara flechas de longe que atravessam um inimigo': 'Shoots arrows from afar that pierce one enemy',
  // raças novas
  'Gnomo': 'Gnome', 'Pequeno, esperto e cheio de sorte.': 'Small, clever and very lucky.', '+2 sorte nos baús': '+2 chest luck',
  'Começa com um Arco Curto': 'Starts with a Short Bow', 'Draconato': 'Dragonborn', 'Sangue de dragão nas veias.': 'Dragon blood in their veins.',
  'Imune ao fogo no chão': 'Immune to fire on the ground', '-10% velocidade de ataque': '-10% attack speed',
  'Morto-Vivo': 'Undead', 'Já morreu uma vez. Não tem medo de nada.': 'Already died once. Fears nothing.', 'Imune a veneno': 'Immune to poison',
  '+2 vida por segundo': '+2 health per second', 'Poções curam -30%': 'Potions heal -30%', '-10% XP': '-10% XP',
  // companheiros novos
  'Gato': 'Cat', 'Arranha e apanha o ouro por ti': 'Scratches and picks up gold for you', 'Coruja': 'Owl',
  'Atira penas e mostra-te o mapa': 'Throws feathers and shows you the map', 'Rochinha': 'Pebble',
  'Bloqueia tiros e esmaga à volta': 'Blocks shots and smashes around it', 'Fénix': 'Phoenix',
  'Fogo e cura-te quando estás quase a morrer': 'Fire, and heals you when you are about to die',
  // dificuldade, bosses, skins
  'Inferno': 'Inferno', 'Desbloqueia ao chegar ao andar 30. O desafio final.': 'Unlocks when you reach floor 30. The final challenge.',
  '(bloq.)': '(locked)', 'Guardião de Cristal': 'Crystal Guardian', 'Senhor do Vazio': 'Void Lord',
  'Cristal': 'Crystal', 'Lendária': 'Legendary', 'Magma': 'Magma',
  // conquistas novas
  'Profundezas': 'Depths', 'Chega ao andar 30 (desbloqueia o Inferno)': 'Reach floor 30 (unlocks Inferno)',
  'Senhor das Zonas': 'Lord of the Zones', 'Chega ao andar 40': 'Reach floor 40', 'Lenda Viva': 'Living Legend', 'Chega ao andar 50': 'Reach floor 50',
  'Quebra-Cristais': 'Crystal Breaker', 'Derrota o Guardião de Cristal': 'Defeat the Crystal Guardian',
  'Luz no Vazio': 'Light in the Void', 'Derrota o Senhor do Vazio': 'Defeat the Void Lord',
  'Exterminador': 'Exterminator', 'Mata 500 monstros (no total)': 'Kill 500 monsters (in total)',
  'Lenda da Matança': 'Slaughter Legend', 'Mata 2000 monstros (no total)': 'Kill 2000 monsters (in total)',
  'Caça-Campeões': 'Champion Hunter', 'Mata 25 Campeões (no total)': 'Kill 25 Champions (in total)',
  'Arqueólogo': 'Archaeologist', 'Junta 5 relíquias na mesma partida': 'Collect 5 relics in one run',
  'Tratador': 'Tamer', 'Liberta 4 companheiros diferentes': 'Free 4 different companions',
  'Olho de Falcão': 'Hawk Eye', 'Mata 100 monstros com arcos (no total)': 'Kill 100 monsters with bows (in total)',
  'Apanha-Ladrões': 'Thief Catcher', 'Mata um goblin que te roubou': 'Kill a goblin that stole from you',
  'Bestiário': 'Bestiary', 'Descobre os 12 monstros novos': 'Discover the 12 new monsters',
  'Intocável': 'Untouchable', 'Derrota um boss sem levar dano': 'Defeat a boss without taking damage',
  'Herói': 'Hero', 'Chega ao nível 30': 'Reach level 30', 'Rei do Inferno': 'King of Inferno', 'Chega ao andar 10 no Inferno': 'Reach floor 10 on Inferno',
  'Diversidade': 'Diversity', 'Chega ao andar 10 com 5 raças diferentes': 'Reach floor 10 with 5 different races',
  // relíquias
  'Relíquias:': 'Relics:', 'Relíquia: ': 'Relic: ', 'x3!': 'x3!', 'Fénix: +': 'Phoenix: +', '+1 Poção (Frasco Eterno)': '+1 Potion (Eternal Flask)',
  'Trevo de 4 Folhas': 'Four-Leaf Clover', '+1 sorte nos baús': '+1 chest luck',
  'Coração de Ouro': 'Golden Heart', '+15% vida máxima': '+15% max health',
  'Luva de Ferro': 'Iron Gauntlet', '+12% dano': '+12% damage',
  'Botas do Vento': 'Wind Boots', '+12% velocidade e esquiva mais rápida': '+12% speed and faster dodge',
  'Ampulheta': 'Hourglass', 'Feitiços recarregam 30% mais depressa': 'Spells recharge 30% faster',
  'Dente de Vampiro': 'Vampire Fang', 'Cada monstro morto cura-te 2% da vida': 'Each monster killed heals you 2% health',
  'Escudo de Espinhos': 'Thorn Shield', 'Devolve 40% do dano que levas': 'Returns 40% of the damage you take',
  'Bolsa Sem Fundo': 'Bottomless Purse', '+35% ouro': '+35% gold',
  'Olho de Águia': 'Eagle Eye', '+10% crítico': '+10% crit',
  'Pena de Fénix': 'Phoenix Feather', 'Revives uma vez com metade da vida': 'You revive once with half health',
  'Cristal de Mana': 'Mana Crystal', '+40 mana e +2 mana por segundo': '+40 mana and +2 mana per second',
  'Grimório Antigo': 'Ancient Grimoire', '+35% poder mágico': '+35% magic power',
  'Frasco Eterno': 'Eternal Flask', 'Ganhas 1 poção em cada andar novo': 'Get 1 potion on every new floor',
  'Floco Eterno': 'Eternal Snowflake', 'Os teus golpes abrandam os inimigos': 'Your hits slow enemies',
  'Brasa Viva': 'Living Ember', 'Os teus golpes queimam os inimigos': 'Your hits burn enemies',
  'Antídoto': 'Antidote', 'Ficas imune a veneno': 'You become immune to poison',
  'Coroa do Rei': "King's Crown", '+25% XP e +15% ouro': '+25% XP and +15% gold',
  'Dado da Sorte': 'Lucky Die', '12% de chance de fazer dano x3': '12% chance to deal x3 damage',
  'Escudo Rúnico': 'Runic Shield', '+25% defesa': '+25% defense',
  'Coleira Dourada': 'Golden Collar', 'O teu companheiro faz o dobro do dano': 'Your companion deals double damage',
  // biomas e monstros novos
  'Pântano Venenoso': 'Poison Swamp', 'Templo do Deserto': 'Desert Temple', 'Caverna de Cristal': 'Crystal Cave', 'Reino do Vazio': 'Void Realm',
  'Goblin Ladrão': 'Thief Goblin', 'Necromante': 'Necromancer', 'Salamandra': 'Salamander', 'Sapo Venenoso': 'Poison Frog',
  'Planta Carnívora': 'Carnivorous Plant', 'Múmia': 'Mummy', 'Escorpião': 'Scorpion', 'Golem de Cristal': 'Crystal Golem',
  'Espírito de Cristal': 'Crystal Spirit', 'Olho do Vazio': 'Void Eye', 'Sombra': 'Shadow', 'Veterano': 'Veteran', 'Campeão': 'Champion',
  'Rouba o teu ouro e foge. Apanha-o para o recuperar!': 'Steals your gold and runs. Catch it to get it back!',
  'Levanta esqueletos e atira magia negra.': 'Raises skeletons and casts dark magic.',
  'Deixa um rasto de fogo por onde passa.': 'Leaves a trail of fire behind it.',
  'Atira bolas de neve e esmaga o chão à sua volta.': 'Throws snowballs and smashes the ground around it.',
  'Salta e cospe veneno.': 'Hops and spits poison.',
  'Não se mexe, mas dispara sementes e morde quem chega perto.': 'Never moves, but shoots seeds and bites anyone who gets close.',
  'Atira ligaduras que te puxam para ela.': 'Throws bandages that pull you in.',
  'Enterra-se na areia e aparece ao teu lado. O ferrão envenena.': 'Burrows into the sand and pops up next to you. Its sting is poisonous.',
  'Quando lhe bates solta estilhaços de cristal.': 'Shoots crystal shards when you hit it.',
  'Teletransporta-se à tua volta e dispara cristais.': 'Teleports around you and shoots crystals.',
  'Aponta e dispara um raio. Sai da linha vermelha!': 'Aims and fires a beam. Get out of the red line!',
  'Quase invisível até estar perto. Rouba-te vida.': 'Almost invisible until close. Drains your life.',
  'Novo monstro: ': 'New monster: ', 'Divide-se!': 'Splits!', 'Gosma!': 'Goo!', 'Suga vida!': 'Life drain!', 'Investida!': 'Charge!',
  'Leque!': 'Spread!', 'Rajada!': 'Burst!', 'Grito de guerra!': 'War cry!', 'Some-se...': 'Vanishes...', 'Teletransporte!': 'Teleport!',
  'Veneno!': 'Poison!', 'Nuvem tóxica!': 'Toxic cloud!', 'Rasto!': 'Trail!', 'Uivo!': 'Howl!', 'Explosão!': 'Blast!', 'Teia!': 'Web!',
  'Bomba!': 'Bomb!', 'Cura!': 'Heal!', 'Envenenado!': 'Poisoned!', 'Puxado!': 'Pulled!', 'Recuperaste o ouro!': 'You got your gold back!',
  'O goblin fugiu!': 'The goblin got away!', 'Levou ': 'Took ', ' de ouro': ' gold', 'ouro!': 'gold!',
  // telemóvel: opções, ecrã inteiro, instalar, tutorial
  'OPÇÕES': 'OPTIONS', 'Opções': 'Options', 'Instalar app': 'Install app', 'Tamanho dos botões': 'Button size',
  'Pequeno': 'Small', 'Grande': 'Large', 'Visibilidade dos botões': 'Button visibility', 'Transparente': 'Transparent',
  'Forte': 'Strong', 'À direita (canhoto)': 'Right (left-handed)', 'À esquerda': 'Left', 'Joystick (direita)': 'Joystick (right)',
  'Vibração': 'Vibration', 'Não suportada': 'Not supported', 'Desligada': 'Off', 'Ligada': 'On', 'Desligado': 'Off', 'Ligado': 'On',
  'Poupança de bateria': 'Battery saver', 'Som do jogo': 'Sound', 'Ecrã inteiro': 'Fullscreen', 'Já está (app)': 'Already (app)',
  'Ver outra vez': 'Show again', 'Toca numa opção para a mudar': 'Tap an option to change it', 'Como fica': 'Preview',
  'O tutorial começa quando voltares ao jogo': 'The tutorial starts when you go back to the game',
  'O tutorial aparece no próximo jogo': 'The tutorial will show in your next game',
  'No iPhone: Partilhar → Adicionar ao ecrã principal': 'On iPhone: Share → Add to Home Screen',
  'Este browser não deixa usar ecrã inteiro': 'This browser does not allow fullscreen',
  'App instalada!': 'App installed!', 'Abre o jogo a partir do ecrã principal': 'Open the game from your home screen',
  'Instalar no iPhone': 'Install on iPhone', 'Toca em Partilhar → Adicionar ao ecrã principal': 'Tap Share → Add to Home Screen',
  'Arrasta o dedo neste lado do ecrã para andar': 'Drag your finger on this side of the screen to move',
  'Toca no botão grande para atacar o inimigo mais perto': 'Tap the big button to attack the nearest enemy',
  'Toca em »» para te esquivares (ficas invencível)': 'Tap »» to dodge (you are invincible)',
  'Lança uma Bola de Fogo (gasta mana)': 'Cast a Fireball (uses mana)',
  'Ao pé de baús, lojas e da escada, toca em USAR': 'Near chests, shops and stairs, tap USE',
  'A poção cura-te. Boa sorte na masmorra!': 'The potion heals you. Good luck in the dungeon!',
  'Os inimigos esperam por ti': 'Enemies will wait for you', 'Saltar': 'Skip',
  'Toca num artigo para o comprar': 'Tap an item to buy it', 'Toca no ecrã para voltar': 'Tap the screen to go back',
  'Toca num item e depois no que queres fazer': 'Tap an item, then what you want to do',
  'Toca numa raça, numa skin e numa dificuldade': 'Tap a race, a skin and a difficulty',
  'Guardar e sair': 'Save and quit', 'Sim, desistir': 'Yes, give up', 'Desistir': 'Give up', 'Não': 'No',
  'Botões, canhoto, vibração, bateria': 'Buttons, left-handed, vibration, battery',
  // som e música
  'Sound: tudo': 'Sound: all', 'Sound: só efeitos': 'Sound: effects only', '[M] Som: tudo': '[M] Sound: all', '[M] Som: só efeitos': '[M] Sound: effects only', 'Som e música': 'Sound and music',
  'Tudo ligado': 'All on', 'Só efeitos': 'Effects only',
  // menu inicial
  'Cidade dos Caçadores': 'Hunter City', 'Desafio Diário': 'Daily Challenge', 'Torre dos 100 Andares': 'Tower of 100 Floors',
  'Almas (': 'Souls (', 'Pacto (Calor ': 'Pact (Heat ', 'Missões': 'Missions', 'Coleção': 'Collection',
  'ENTER: jogar · N: novo · C: cidade · D: diário · O: torre · A: almas · K: pacto · L: coleção · T: conquistas · R: missões · I: idioma': 'ENTER: play · N: new · C: city · D: daily · O: tower · A: souls · K: pact · L: collection · T: achievements · R: missions · I: language',
  'Cada baú pode dar o PIOR ou o MELHOR item!': 'Every chest can give the WORST or the BEST item!',
  'Botões ★ e de magia': '★ and spell buttons', 'Magias, habilidades e poder único': 'Spells, skills and unique power',
  // cidade
  'CIDADE DOS CAÇADORES': 'HUNTER CITY', 'Moedas: ': 'Coins: ', 'Rank de caçador: ': 'Hunter rank: ',
  'Associação de Caçadores': 'Hunter Association', 'Ferreiro': 'Blacksmith', 'Alquimista': 'Alchemist', 'Portão da Masmorra': 'Dungeon Gate',
  'Reavaliação de rank (precisas de poder ': 'Rank reassessment (you need power ', 'Reavaliação: rank máximo': 'Reassessment: max rank',
  'Já és um Caçador de Nível Nacional!': 'You are already a National Level Hunter!',
  'O cristal não reage. Precisas de mostrar poder ': 'The crystal does not react. You need to show power ', ' (o teu melhor: ': ' (your best: ',
  'REAVALIADO! Agora és Caçador de Rank ': 'REASSESSED! You are now a Rank ', '[Sistema] Reavaliação concluída': '[System] Reassessment complete',
  'Mata {n} monstros de elite': 'Kill {n} elite monsters', 'Mata {n} monstros': 'Kill {n} monsters', 'Derrota {n} bosses': 'Defeat {n} bosses',
  'Conquista {n} portais': 'Clear {n} gates', 'Abre {n} baús': 'Open {n} chests', 'Chega ao andar {n}': 'Reach floor {n}',
  'Contrato cumprido!': 'Contract complete!', 'Recebe o prémio na Associação de Caçadores': 'Collect the reward at the Hunter Association',
  'Contrato entregue: +': 'Contract delivered: +', 'Ainda não cumpriste este contrato': 'You have not completed this contract yet',
  'Receber ': 'Collect ', ' moedas': ' coins',
  'Forjar a arma inicial': 'Forge the starting weapon', 'Começas com a arma +1 (até +5)': 'Start with the weapon +1 (up to +5)',
  'Armadura de caçador': 'Hunter armour', 'Começas com uma armadura Comum, Rara ou Épica': 'Start with a Common, Rare or Epic armour',
  'Bolsa de poções': 'Potion pouch', '+1 poção no início (até +3)': '+1 potion at the start (up to +3)',
  'Receita melhorada': 'Better recipe', 'Poções curam +5% (até +15%)': 'Potions heal +5% (up to +15%)',
  'Elixir de mana': 'Mana elixir', '+15 mana máxima (até +45)': '+15 max mana (up to +45)',
  'Já está no máximo': 'Already at max', 'Não tens moedas suficientes. Joga mais partidas!': 'Not enough coins. Play more runs!',
  'Masmorra normal': 'Normal dungeon', ' (já jogado hoje)': ' (already played today)',
  'A Associação mede o teu poder.': 'The Association measures your power.', 'O teu melhor poder: ': 'Your best power: ',
  'Cada rank dá +3% dano e +3% vida': 'Each rank gives +3% damage and +3% health', 'para sempre (Rank S: +1 poção).': 'forever (Rank S: +1 potion).',
  'Contratos dão moedas de caçador.': 'Contracts give hunter coins.',
  'O ferreiro prepara o teu equipamento': 'The blacksmith prepares your gear', 'para a próxima entrada na masmorra.': 'for your next dungeon run.',
  'O alquimista enche a tua bolsa': 'The alchemist fills your pouch', 'antes de cada partida.': 'before every run.',
  'Escolhe como queres entrar:': 'Choose how to go in:', 'Normal: a masmorra de sempre': 'Normal: the usual dungeon',
  'Diário: mesmo mapa para todos, hoje': 'Daily: same map for everyone today', 'Torre: 100 andares de arenas': 'Tower: 100 floors of arenas',
  'Ganhas moedas no fim de cada partida (15% do ouro + andar + bosses)': 'You earn coins at the end of every run (15% of gold + floor + bosses)',
  '1-4 / A D: edifício · W S: escolher · E: comprar · Esc: voltar': '1-4 / A D: building · W S: choose · E: buy · Esc: back',
  ' moedas de caçador para a Cidade (tens ': ' hunter coins for the City (you have ',
  // desafio diário
  'DESAFIO DIÁRIO': 'DAILY CHALLENGE', 'Hoje: ': 'Today: ', ' · os mapas de hoje são iguais para toda a gente': ' · today\'s maps are the same for everyone',
  'Pactos de hoje:': 'Today\'s pacts:', 'As tuas pontuações': 'Your scores', 'Ainda não jogaste nenhum desafio': 'You have not played a challenge yet',
  ' (hoje)': ' (today)', 'Pontos: andar x1000 + monstros x5 + nível x20 + bosses x300': 'Points: floor x1000 + monsters x5 + level x20 + bosses x300',
  'ENTER: Começar o desafio': 'ENTER: Start the challenge', 'Começar o desafio': 'Start the challenge',
  'Desafio Diário: ': 'Daily Challenge: ', ' pontos': ' points', ' · NOVO RECORDE DE HOJE!': ' · NEW RECORD FOR TODAY!',
  // torre
  'TORRE · ANDAR ': 'TOWER · FLOOR ', 'TORRE: CRIA A TUA PERSONAGEM': 'TOWER: CREATE YOUR CHARACTER', 'TORRE ': 'TOWER ',
  'Andar de descanso: loja, encantamentos e um baú': 'Rest floor: shop, enchanting and a chest', 'Sobrevive a ': 'Survive ', ' ondas': ' waves',
  'ANDAR LIMPO!': 'FLOOR CLEARED!', 'Abre o baú e sobe a escada': 'Open the chest and climb the stairs',
  'CONQUISTASTE A TORRE!': 'YOU CONQUERED THE TOWER!', 'Os 100 andares são teus. Continua, se tiveres coragem...': 'The 100 floors are yours. Keep going, if you dare...',
  'Torre: chegaste ao andar ': 'Tower: you reached floor ', ' (recorde ': ' (record ',
  // mudança de classe
  '+60% poder mágico e Bola de Fogo nível 2': '+60% magic power and Fireball level 2',
  '+2 vida/s, poções +15% e +30% poder mágico': '+2 health/s, potions +15% and +30% magic power',
  'Herói Lendário': 'Legendary Hero', '+20% XP e +60 vida': '+20% XP and +60 health', 'Golpe Heróico': 'Heroic Strike',
  'Um corte enorme em leque à tua frente (dano x4)': 'A huge fan-shaped slash in front of you (damage x4)',
  'Monarca das Sombras': 'Shadow Monarch', '+7 sombras e as sombras fazem +40% dano': '+7 shadows and shadows deal +40% damage',
  'Trocas de lugar com a tua sombra mais longe (recarga 5 s)': 'Swap places with your farthest shadow (5 s cooldown)',
  'Espada Santa': 'Holy Sword', '+25% vel. de ataque e +12% crítico': '+25% attack speed and +12% crit',
  'Atravessa os monstros num relâmpago (dano x5)': 'Dash through monsters like lightning (damage x5)',
  'Monarca das Chamas': 'Flame Monarch', '+100% poder mágico': '+100% magic power', 'Uma chuva de 14 meteoros de fogo': 'A rain of 14 fire meteors',
  'Rei das Feras': 'King of Beasts', '+120 vida': '+120 health', 'Forma de fera durante 14 s: +50% dano, +30% velocidade e roubo de vida': 'Beast form for 14 s: +50% damage, +30% speed and life steal',
  'Rei Titã': 'Titan King', '+160 vida e +12 defesa, -10% velocidade': '+160 health and +12 defense, -10% speed',
  'Esmaga o chão num raio enorme e levas -50% dano durante 4 s': 'Smash the ground in a huge radius and take -50% damage for 4 s',
  'Santo': 'Saint', '+4 vida/s, poções +20% e +50% poder mágico': '+4 health/s, potions +20% and +50% magic power',
  'Cura 40% da vida e queima os monstros à volta (x2 em mortos-vivos)': 'Heals 40% health and burns nearby monsters (x2 vs undead)',
  'Senhor da Tempestade': 'Storm Lord', '+25% velocidade': '+25% speed', 'Um leque de 9 lâminas de vento': 'A fan of 9 wind blades',
  '[Sistema] Missão de Mudança de Classe': '[System] Job Change Quest', 'O próximo andar é a tua Provação. Vence-a para evoluir!': 'The next floor is your Trial. Win it to evolve!',
  'Provação: ': 'Trial: ', 'PROVAÇÃO DE CLASSE': 'JOB CHANGE TRIAL', 'MUDANÇA DE CLASSE!': 'JOB CHANGE!', '[Sistema] Agora és ': '[System] You are now ',
  // generais sombra
  '[Sistema] Novo general: ': '[System] New general: ', 'Um boss juntou-se ao teu Exército das Sombras': 'A boss joined your Shadow Army',
  'Cavaleiro Sombrio': 'Shadow Knight', 'Gelatinoso': 'Gelatinous', 'Arquimago Negro': 'Black Archmage', 'Asa da Noite': 'Nightwing',
  'Rocha Eterna': 'Eternal Rock', 'Rainha Tecelã': 'Weaver Queen', 'Chifre Negro': 'Black Horn', 'Guarda Cristalino': 'Crystal Guard',
  'Eco do Vazio': 'Void Echo', 'General Sombrio': 'Shadow General', ' soldados · ': ' soldiers · ', ' generais': ' generals',
  // masmorra dupla
  'MASMORRA DUPLA': 'DOUBLE DUNGEON', 'Regra 1: Venera o deus.': 'Rule 1: Worship the god.', 'Regra 2: Louva o deus.': 'Rule 2: Praise the god.',
  'Regra 3: Prova a tua fé.': 'Rule 3: Prove your faith.', 'NÃO TE MEXAS!': 'DON\'T MOVE!', 'A estátua está a olhar para ti': 'The statue is looking at you',
  'Os olhos apagam-se...': 'The eyes go dark...', 'Podes mexer-te': 'You can move', 'Os guardiões acordam!': 'The guardians awaken!',
  'Guardião de Pedra': 'Stone Guardian', 'a Estátua do Deus': 'the God Statue', 'PROVASTE A TUA FÉ!': 'YOU PROVED YOUR FAITH!',
  '+30 almas · a estátua desfez-se: abre os baús e sai': '+30 souls · the statue crumbled: open the chests and leave',
  'Sobrevive: ': 'Survive: ', 'Porta Antiga': 'Ancient Door', 'Uma masmorra dentro da masmorra. Sente-se algo a observar...': 'A dungeon inside the dungeon. Something is watching...',
  ': Entrar (não há volta até ao fim)': ': Enter (no way back until the end)',
  // conquistas novas
  'Caçador de Rank S': 'Rank S Hunter', 'Passa a Rank S na reavaliação': 'Reach Rank S in the reassessment',
  'Desafiante': 'Challenger', 'Chega ao andar 10 no Desafio Diário': 'Reach floor 10 in the Daily Challenge',
  'Alpinista': 'Climber', 'Chega ao andar 25 da Torre': 'Reach floor 25 of the Tower',
  'Senhor da Torre': 'Lord of the Tower', 'Conquista os 100 andares da Torre': 'Clear the 100 floors of the Tower',
  'Mudança de Classe': 'Job Change', 'Passa a provação do nível 30': 'Pass the level 30 trial',
  'Primeiro General': 'First General', 'Ergue um boss como general sombra': 'Raise a boss as a shadow general',
  'Sobrevive ao Templo da Masmorra Dupla': 'Survive the Double Dungeon Temple',
  // magias e habilidades por caçador
  'Começa a saber Relâmpago (se o caçador usar)': 'Start knowing Lightning (if your hunter uses it)',
  'Todas as magias do caçador no nível 3': 'All your hunter\'s spells at level 3',
  'Redemoinho': 'Whirlwind', 'Giras a arma e cortas todos os monstros à tua volta': 'Spin your weapon and cut every monster around you',
  'Investida': 'Charge', 'Carregas em frente e atordoas os monstros que atropelas': 'Charge forward and stun the monsters you run over',
  'Mil Cortes': 'Thousand Cuts', 'Saltas para o monstro mais perto e cortas 6 vezes seguidas': 'Leap to the nearest monster and slash 6 times',
  'Rio de Chamas': 'River of Flames', 'Uma linha de explosões de fogo à tua frente': 'A line of fire explosions in front of you',
  'Supernova': 'Supernova', 'Uma explosão enorme à tua volta que queima tudo': 'A huge explosion around you that burns everything',
  'Rugido': 'Roar', 'Os monstros fogem de medo e ganhas +25% dano durante 6 s': 'Monsters flee in fear and you get +25% damage for 6 s',
  'Grito de Guerra': 'War Cry', 'Durante 6 s levas -40% dano': 'Take -40% damage for 6 s',
  'Onda de Choque': 'Shockwave', 'Um soco no ar que esmaga e empurra os monstros à tua frente': 'A punch in the air that crushes and pushes monsters in front of you',
  'Barreira Sagrada': 'Holy Barrier', 'Um escudo de luz absorve dano (25% da tua vida) durante 8 s': 'A shield of light absorbs damage (25% of your health) for 8 s',
  'Julgamento': 'Judgement', 'Pilares de luz caem sobre os 4 monstros mais perto (x2 em mortos-vivos)': 'Pillars of light strike the 4 nearest monsters (x2 vs undead)',
  'Tornado': 'Tornado', 'Um tornado lento que atravessa e corta tudo no caminho': 'A slow tornado that passes through and cuts everything in its way',
  'RUGIDO!': 'ROAR!', 'GRITO DE GUERRA': 'WAR CRY', 'Nenhum monstro perto': 'No monster nearby',
  'O teu caçador não usa esta magia': 'Your hunter does not use this spell',
  'O teu caçador não usa magias: usa as habilidades (5 a 8)': 'Your hunter uses no spells: use the skills (5 to 8)',
  'Este caçador não tem habilidades extra': 'This hunter has no extra skills',
  'Sem habilidade única': 'No unique ability', 'Magias: ': 'Spells: ', 'nenhuma': 'none', 'Habilidades: ': 'Skills: ',
  'CAÇADOR: ': 'HUNTER: ', 'Passiva: ': 'Passive: ', 'Espera ': 'Wait ', 'Novo botão': 'New button', 'Tens um botão novo': 'You have a new button',
  '+2 vida por segundo e poções +15%': '+2 health per second and potions +15%',
  // portais
  'Andar de Rank ': 'Floor Rank ', ' · Rank do andar ': ' · Floor rank ', 'MORTAL': 'DEADLY', 'Rutura em ': 'Break in ',
  'RUTURA DO PORTAL!': 'DUNGEON BREAK!', 'Os monstros do portal Rank ': 'The monsters of the Rank ', ' saíram para a masmorra': ' gate escaped into the dungeon',
  'Sentes um portal: Rank ': 'You sense a gate: Rank ', 'Sentes portais: Rank ': 'You sense gates: Rank ', ' e ': ' and ', ' (vê o minimapa)': ' (see the minimap)',
  // tutorial
  'Tutorial ': 'Tutorial ',
  'Anda com W A S D ou as setas': 'Move with W A S D or the arrow keys',
  'Ataca: clica com o rato (ou Espaço)': 'Attack: click the mouse (or Space)',
  'Toca no botão grande para atacar': 'Tap the big button to attack',
  'Vai até ao baú (seta amarela) e carrega E para o abrir': 'Go to the chest (yellow arrow) and press E to open it',
  'Vai até ao baú (seta amarela) e toca em USAR': 'Go to the chest (yellow arrow) and tap USE',
  'Abre a mochila com a tecla I: lá equipas ou vendes itens': 'Open the backpack with I: equip or sell items there',
  'Toca no saco para abrir a mochila: lá equipas ou vendes itens': 'Tap the bag to open the backpack: equip or sell items there',
  'Carrega U para abrir a Janela de Estado e gastar pontos': 'Press U to open the Status Window and spend points',
  'Toca no herói e depois em Estado para gastar pontos': 'Tap the hero and then Status to spend points',
  'Q bebe uma poção (cura). Experimenta agora': 'Q drinks a potion (heals). Try it now',
  'O botão da poção cura-te. Experimenta agora': 'The potion button heals you. Try it now',
  'Mata monstros e encontra a escada (vê o minimapa). Os portais são opcionais... e perigosos!': 'Kill monsters and find the stairs (see the minimap). Gates are optional... and dangerous!',
  'Toca no botão de ': 'Tap the button of ', ' para lançar magia': ' to cast magic', 'Carrega 1 para lançar ': 'Press 1 to cast ', ' (gasta mana)': ' (uses mana)',
  'Toca em ★ para usar ': 'Tap ★ to use ', 'Carrega F para usar ': 'Press F to use ',
  'Toca em »» para te esquivares': 'Tap »» to dodge', 'Shift: esquiva (ficas invencível)': 'Shift: dodge (you are invincible)',
};

const LISTA_EN = Object.entries(EN).filter(([a, b]) => a !== b).sort((a, b) => b[0].length - a[0].length);
const cacheTraducao = new Map();

function traduzir(txt) {
  if (idioma === 'pt' || txt == null) return txt;
  txt = String(txt);
  let r = cacheTraducao.get(txt);
  if (r !== undefined) return r;
  r = txt;
  for (const [a, b] of LISTA_EN) if (r.includes(a)) r = r.split(a).join(b);
  if (cacheTraducao.size > 4000) cacheTraducao.clear();
  cacheTraducao.set(txt, r);
  return r;
}

function mudarIdioma() {
  idioma = idioma === 'pt' ? 'en' : 'pt';
  try { localStorage.setItem('masmorra_idioma', idioma); } catch (e) { /* sem storage */ }
  document.documentElement.lang = idioma;
  document.title = idioma === 'en' ? 'Dungeon of Destiny' : 'Masmorra do Destino';
}
document.documentElement.lang = idioma;
if (idioma === 'en') document.title = 'Dungeon of Destiny';

// Botão PT | EN (no menu inicial e na pausa)
const BOTAO_IDIOMA = { x: LARGURA - 128, y: 14, w: 112, h: 36 };
