"""Faz os sprites HD de uma lista: render no Blender + pixel art.
    python3 lote.py slime morcego ...   (sem nomes = todos)
Cada entrada: nome -> (modelo, variáveis de ambiente, largura, altura, opções do pixel.py)
As medidas são o dobro das dos sprites antigos (mesmo tamanho no ecrã, dobro do detalhe).
"""
import subprocess, sys, os
from concurrent.futures import ThreadPoolExecutor
AQUI = os.path.dirname(os.path.abspath(__file__))

LISTA = {
    'slime':         ('slime', {'COR': 'verde'}, 32, 24, ['--extra', '#ffffff,#1b1424']),
    'slimeLava':     ('slime', {'COR': 'lava'}, 32, 24, ['--extra', '#ffffff,#1b1424,#ffd23f']),
    'morcego':       ('morcego', {}, 32, 20, ['--ancora', 'centro', '--extra', '#ff3b3b']),
    'esqueleto':     ('esqueleto', {}, 32, 32, ['--extra', '#ff3b3b,#1b1424']),
    'orc':           ('orc', {}, 32, 32, ['--extra', '#ffd23f,#e8e2cf']),
    'fantasma':      ('fantasma', {}, 32, 32, ['--extra', '#1b1424']),
    'aranha':        ('aranha', {}, 32, 20, ['--extra', '#ff3b3b']),
    'mimico':        ('bau', {'TIPO': 'mimico'}, 32, 32, ['--extra', '#f1ece0,#ffd23f,#8a1a2a']),
    'bau.madeira':   ('bau', {'TIPO': 'madeira'}, 32, 28, ['--extra', '#ffd23f']),
    'bau.ouro':      ('bau', {'TIPO': 'ouro'}, 32, 28, ['--extra', '#e04848']),
    'bau.maldito':   ('bau', {'TIPO': 'maldito'}, 32, 28, ['--extra', '#e04848']),
    'zumbi':         ('zumbi', {}, 32, 32, ['--extra', '#ffd23f']),
    'diabrete':      ('diabrete', {}, 32, 26, ['--extra', '#ffd23f,#f1ece0']),
    'loboGelo':      ('loboGelo', {}, 32, 20, ['--extra', '#6fd8ff,#1b1424']),
    'elementalGelo': ('elementalGelo', {}, 32, 22, ['--ancora', 'centro']),
    'goblin':        ('goblin', {}, 32, 32, ['--extra', '#ffd23f,#1b1424']),
    'necromante':    ('necromante', {}, 32, 32, ['--extra', '#6ff8ff']),
    'salamandra':    ('salamandra', {}, 32, 18, ['--extra', '#ffd23f']),
    'yeti':          ('yeti', {}, 36, 34, ['--extra', '#1b1424,#ffffff']),
    'sapo':          ('sapo', {}, 32, 22, ['--extra', '#1b1424,#ffffff']),
    'planta':        ('planta', {}, 32, 34, ['--extra', '#ffffff']),
    'mumia':         ('mumia', {}, 32, 28, ['--extra', '#6fff6a,#1b1424']),
    'escorpiao':     ('escorpiao', {}, 32, 28, []),
    'golemCristal':  ('golemCristal', {}, 36, 32, ['--extra', '#6fd8ff']),
    'espiritoCristal': ('espiritoCristal', {}, 32, 30, ['--ancora', 'centro', '--extra', '#ffffff']),
    'olhoVazio':     ('olhoVazio', {}, 32, 30, ['--ancora', 'centro', '--extra', '#1b1424,#ff3b6a']),
    'sombra':        ('sombra', {}, 32, 30, ['--extra', '#c06aff']),
    'anjoGuerreiro': ('anjo', {'TIPO': 'guerreiro'}, 32, 32, ['--extra', '#ffe680,#1b1424']),
    'arqueiroCeleste': ('anjo', {'TIPO': 'arqueiro'}, 32, 32, ['--extra', '#ffe680,#1b1424']),
    'querubim':      ('querubim', {}, 32, 32, ['--ancora', 'centro', '--extra', '#1b1424,#ffe680']),
    'cavaleiroVazio': ('cavaleiroVazio', {}, 32, 32, ['--extra', '#ff3b3b']),
    'magoVazio':     ('magoVazio', {}, 32, 32, ['--extra', '#ff6aff']),
    'devorador':     ('devorador', {}, 32, 32, ['--extra', '#ffd23f,#f1ece0']),
    'reiSlime':      ('reiSlime', {}, 100, 92, ['--cores', '16', '--extra', '#ffffff,#1b1424,#ffd23f,#e04848']),
    'lich':          ('lich', {}, 68, 84, ['--cores', '16', '--extra', '#6ff8ff,#1b1424,#ffd23f']),
    'dragao':        ('dragao', {}, 120, 100, ['--cores', '16', '--extra', '#ffd23f,#1b1424,#f1ece0']),
    'golem':         ('golem', {}, 112, 112, ['--cores', '16', '--extra', '#ffb03a,#ff8a2a']),
    'rainha':        ('rainha', {}, 120, 88, ['--cores', '16', '--extra', '#ff3b3b,#ffd23f']),
    'demonio':       ('demonio', {}, 112, 100, ['--cores', '16', '--extra', '#ffd23f,#f1ece0,#1b1424']),
    'guardiao':      ('guardiao', {}, 88, 92, ['--cores', '16', '--extra', '#6fd8ff,#ff8ad8']),
    'senhorVazio':   ('senhorVazio', {}, 76, 92, ['--cores', '16', '--extra', '#ff3b6a,#c06aff']),
    'arcanjo':       ('arcanjo', {}, 104, 108, ['--cores', '16', '--extra', '#ffe680,#6fd8ff']),
    'generalMonarca': ('generalMonarca', {}, 108, 112, ['--cores', '16', '--extra', '#c06aff,#b48aff']),
    'carrasco':      ('carrasco', {}, 120, 116, ['--cores', '16', '--extra', '#ff3b3b']),
    'monarca':       ('monarca', {}, 128, 140, ['--cores', '16', '--extra', '#c06aff,#ffd23f,#c99a1e']),
    'decor.0.0.c': ('props', {'TIPO': 'osso'}, 32, 32, ['--caixa', '2,12,28,18', '--cores', '12']),
    'decor.0.1.c': ('props', {'TIPO': 'cranio'}, 32, 32, ['--caixa', '6,12,20,16', '--cores', '12']),
    'decor.0.2.c': ('props', {'TIPO': 'pedras', 'COR': '#6a6878'}, 32, 32, ['--caixa', '4,16,24,12', '--cores', '12']),
    'decor.0.3.c': ('props', {'TIPO': 'barril'}, 32, 32, ['--caixa', '6,6,20,24', '--cores', '12']),
    'decor.1.0.c': ('props', {'TIPO': 'lapide'}, 32, 32, ['--caixa', '6,8,20,22', '--cores', '12']),
    'decor.1.1.c': ('props', {'TIPO': 'lapide', 'COR': 'musgo'}, 32, 32, ['--caixa', '4,8,24,22', '--cores', '12']),
    'decor.1.2.c': ('props', {'TIPO': 'cruz'}, 32, 32, ['--caixa', '8,4,20,28', '--cores', '12']),
    'decor.1.3.c': ('props', {'TIPO': 'osso'}, 32, 32, ['--caixa', '2,12,28,18', '--cores', '12']),
    'decor.2.0.c': ('props', {'TIPO': 'fenda'}, 32, 32, ['--caixa', '6,10,26,8', '--cores', '12']),
    'decor.2.1.c': ('props', {'TIPO': 'fenda', 'COR': 'b'}, 32, 32, ['--caixa', '6,16,26,8', '--cores', '12']),
    'decor.2.2.c': ('props', {'TIPO': 'pedras', 'COR': '#5a3a2a'}, 32, 32, ['--caixa', '4,16,24,12', '--cores', '12']),
    'decor.2.3.c': ('props', {'TIPO': 'osso'}, 32, 32, ['--caixa', '2,12,28,18', '--cores', '12']),
    'decor.3.0.c': ('props', {'TIPO': 'espinhosGelo'}, 32, 32, ['--caixa', '8,6,22,24', '--cores', '12']),
    'decor.3.1.c': ('props', {'TIPO': 'espinhosGelo', 'COR': 'b'}, 32, 32, ['--caixa', '8,10,22,20', '--cores', '12']),
    'decor.3.2.c': ('props', {'TIPO': 'neve'}, 32, 32, ['--caixa', '4,18,24,12', '--cores', '12']),
    'decor.4.0.c': ('props', {'TIPO': 'cogumelo', 'COR': '#6fdd4a'}, 32, 32, ['--caixa', '6,10,24,22', '--cores', '12']),
    'decor.4.1.c': ('props', {'TIPO': 'cogumelo', 'COR': '#b06aff'}, 32, 32, ['--caixa', '6,10,24,22', '--cores', '12']),
    'decor.4.2.c': ('props', {'TIPO': 'juncos'}, 32, 32, ['--caixa', '6,8,22,24', '--cores', '12']),
    'decor.5.0.c': ('props', {'TIPO': 'vaso'}, 32, 32, ['--caixa', '6,8,20,22', '--cores', '12']),
    'decor.5.1.c': ('props', {'TIPO': 'pilar'}, 32, 32, ['--caixa', '6,6,20,24', '--cores', '12']),
    'decor.5.2.c': ('props', {'TIPO': 'areia'}, 32, 32, ['--caixa', '4,20,24,8', '--cores', '12']),
    'decor.5.3.c': ('props', {'TIPO': 'cranio'}, 32, 32, ['--caixa', '6,12,20,16', '--cores', '12']),
    'decor.6.0.c': ('props', {'TIPO': 'cristais', 'COR': '#6fd8ff'}, 32, 32, ['--caixa', '6,6,24,24', '--cores', '12']),
    'decor.6.1.c': ('props', {'TIPO': 'cristais', 'COR': '#ff8ad8'}, 32, 32, ['--caixa', '6,6,24,24', '--cores', '12']),
    'decor.6.2.c': ('props', {'TIPO': 'cristais', 'COR': '#b48aff'}, 32, 32, ['--caixa', '6,6,24,24', '--cores', '12']),
    'decor.6.3.c': ('props', {'TIPO': 'pedras', 'COR': '#3a4a6a'}, 32, 32, ['--caixa', '4,16,24,12', '--cores', '12']),
    'decor.7.0.c': ('props', {'TIPO': 'runa'}, 32, 32, ['--caixa', '6,12,22,14', '--cores', '12']),
    'decor.7.1.c': ('props', {'TIPO': 'obelisco'}, 32, 32, ['--caixa', '8,4,16,28', '--cores', '12']),
    'decor.7.2.c': ('props', {'TIPO': 'pedras', 'COR': '#2a2238'}, 32, 32, ['--caixa', '4,16,24,12', '--cores', '12']),
    'decor.8.0.c': ('props', {'TIPO': 'estalagmite', 'COR': '#e8d890'}, 32, 32, ['--caixa', '8,8,16,22', '--cores', '12']),
    'decor.8.1.c': ('props', {'TIPO': 'estalagmite', 'COR': '#f1ece0'}, 32, 32, ['--caixa', '8,8,16,22', '--cores', '12']),
    'decor.8.2.c': ('props', {'TIPO': 'estalagmite', 'COR': '#e8d890'}, 32, 32, ['--caixa', '8,8,16,22', '--cores', '12']),
    'decor.8.3.c': ('props', {'TIPO': 'pedras', 'COR': '#a8a8c0'}, 32, 32, ['--caixa', '4,16,24,12', '--cores', '12']),
    'decor.9.0.c': ('props', {'TIPO': 'osso'}, 32, 32, ['--caixa', '2,12,28,18', '--cores', '12']),
    'decor.9.1.c': ('props', {'TIPO': 'cranio'}, 32, 32, ['--caixa', '6,12,20,16', '--cores', '12']),
    'decor.9.2.c': ('props', {'TIPO': 'runa', 'COR': '#8a6aff', 'TRACO': '1'}, 32, 32, ['--caixa', '6,12,22,14', '--cores', '12']),
    'decor.9.3.c': ('props', {'TIPO': 'pedras', 'COR': '#2a2238'}, 32, 32, ['--caixa', '4,16,24,12', '--cores', '12']),
    'pocao': ('objetos', {'TIPO': 'pocao'}, 20, 22, ['--caixa', '0,0,20,22', '--extra', '#ffffff']),
    'moeda': ('objetos', {'TIPO': 'moeda'}, 12, 12, ['--caixa', '0,0,12,12', '--cores', '8']),
    'mercador': ('objetos', {'TIPO': 'mercador'}, 32, 36, ['--extra', '#1b1424']),
    'altar': ('objetos', {'TIPO': 'altar'}, 40, 30, ['--caixa', '2,0,36,30', '--extra', '#ffb03a,#e04848']),
    'altarUsado': ('objetos', {'TIPO': 'altar', 'FASE': 'usado'}, 40, 30, ['--caixa', '2,2,36,28', ]),
    'cristal.inativo': ('objetos', {'TIPO': 'cristal', 'FASE': 'inativo'}, 24, 38, ['--caixa', '0,0,24,38', ]),
    'cristal.ativo': ('objetos', {'TIPO': 'cristal', 'FASE': 'ativo'}, 24, 38, ['--caixa', '0,0,24,38', ]),
    'cristal.feito': ('objetos', {'TIPO': 'cristal', 'FASE': 'feito'}, 24, 38, ['--caixa', '0,0,24,38', ]),
    'tocha': ('objetos', {'TIPO': 'tocha'}, 12, 20, ['--caixa', '0,0,12,20', '--cores', '10']),
    'mesa': ('objetos', {'TIPO': 'mesa'}, 40, 28, ['--caixa', '2,0,36,28', ]),
    'gaiola': ('objetos', {'TIPO': 'gaiola'}, 40, 44, ['--caixa', '0,0,40,44', ]),
    'livro.fogo': ('objetos', {'TIPO': 'livro', 'COR': 'fogo'}, 24, 28, ['--caixa', '2,0,22,28', '--cores', '10']),
    'livro.raio': ('objetos', {'TIPO': 'livro', 'COR': 'raio'}, 24, 28, ['--caixa', '2,0,22,28', '--cores', '10']),
    'feitico.raio': ('objetos', {'TIPO': 'feitico', 'COR': 'raio'}, 32, 32, ['--caixa', '6,0,20,28', '--cores', '10', '--ancora', 'centro']),
    'livro.gelo': ('objetos', {'TIPO': 'livro', 'COR': 'gelo'}, 24, 28, ['--caixa', '2,0,22,28', '--cores', '10']),
    'feitico.gelo': ('objetos', {'TIPO': 'feitico', 'COR': 'gelo'}, 32, 32, ['--caixa', '2,2,30,30', '--cores', '10', '--ancora', 'centro']),
    'livro.cura': ('objetos', {'TIPO': 'livro', 'COR': 'cura'}, 24, 28, ['--caixa', '2,0,22,28', '--cores', '10']),
    'pet.lobo': ('pets', {'TIPO': 'lobo'}, 32, 20, ['--caixa', '2,0,30,20', '--cores', '14']),
    'pet.dragao': ('pets', {'TIPO': 'dragao'}, 32, 22, ['--caixa', '0,0,32,22', '--cores', '14']),
    'pet.gato': ('pets', {'TIPO': 'gato'}, 24, 20, ['--caixa', '0,0,24,20', '--cores', '14']),
    'pet.coruja': ('pets', {'TIPO': 'coruja'}, 24, 22, ['--caixa', '0,0,24,22', '--cores', '14']),
    'pet.rochinha': ('pets', {'TIPO': 'rochinha'}, 24, 20, ['--caixa', '0,0,24,20', '--cores', '14']),
    'tochaZona.0': ('objetos', {'TIPO': 'tocha', 'COR': '#ff9a2a'}, 12, 20, ['--caixa', '0,0,12,20', '--cores', '10']),
    'tochaZona.1': ('objetos', {'TIPO': 'tocha', 'COR': '#9aff3a'}, 12, 20, ['--caixa', '0,0,12,20', '--cores', '10']),
    'tochaZona.2': ('objetos', {'TIPO': 'tocha', 'COR': '#ff9a2a'}, 12, 20, ['--caixa', '0,0,12,20', '--cores', '10']),
    'tochaZona.3': ('objetos', {'TIPO': 'tocha', 'COR': '#6fd8ff'}, 12, 20, ['--caixa', '0,0,12,20', '--cores', '10']),
    'tochaZona.4': ('objetos', {'TIPO': 'tocha', 'COR': '#c06aff'}, 12, 20, ['--caixa', '0,0,12,20', '--cores', '10']),
    'tochaZona.5': ('objetos', {'TIPO': 'tocha', 'COR': '#fff3a8'}, 12, 20, ['--caixa', '0,0,12,20', '--cores', '10']),
    'tochaZona.6': ('objetos', {'TIPO': 'tocha', 'COR': '#7a6aff'}, 12, 20, ['--caixa', '0,0,12,20', '--cores', '10']),
    'tochaZona.7': ('objetos', {'TIPO': 'tocha', 'COR': '#ff9a2a'}, 12, 20, ['--caixa', '0,0,12,20', '--cores', '10']),
    'tochaZona.8': ('objetos', {'TIPO': 'tocha', 'COR': '#ff9a2a'}, 12, 20, ['--caixa', '0,0,12,20', '--cores', '10']),
    'tochaZona.9': ('objetos', {'TIPO': 'tocha', 'COR': '#ff9a2a'}, 12, 20, ['--caixa', '0,0,12,20', '--cores', '10']),
    'icone.espada': ('icone', {'TIPO': 'espada'}, 32, 32, ['--cores', '12', '--ancora', 'centro', '--extra', '#5b5b5b,#898989,#b0b0b0,#c5c5c5']),
    'icone.adaga': ('icone', {'TIPO': 'adaga'}, 32, 32, ['--cores', '12', '--ancora', 'centro', '--extra', '#5b5b5b,#898989,#b0b0b0,#c5c5c5']),
    'icone.machado': ('icone', {'TIPO': 'machado'}, 32, 32, ['--cores', '12', '--ancora', 'centro', '--extra', '#5b5b5b,#898989,#b0b0b0,#c5c5c5']),
    'icone.lanca': ('icone', {'TIPO': 'lanca'}, 32, 32, ['--cores', '12', '--ancora', 'centro', '--extra', '#5b5b5b,#898989,#b0b0b0,#c5c5c5']),
    'icone.martelo': ('icone', {'TIPO': 'martelo'}, 32, 32, ['--cores', '12', '--ancora', 'centro', '--extra', '#5b5b5b,#898989,#b0b0b0,#c5c5c5']),
    'icone.foice': ('icone', {'TIPO': 'foice'}, 32, 32, ['--cores', '12', '--ancora', 'centro', '--extra', '#5b5b5b,#898989,#b0b0b0,#c5c5c5']),
    'icone.arco': ('icone', {'TIPO': 'arco'}, 32, 32, ['--cores', '12', '--ancora', 'centro', '--extra', '#5b5b5b,#898989,#b0b0b0,#c5c5c5']),
    'icone.cajado': ('icone', {'TIPO': 'cajado'}, 32, 32, ['--cores', '12', '--ancora', 'centro', '--extra', '#5b5b5b,#898989,#b0b0b0,#c5c5c5']),
    'icone.colher': ('icone', {'TIPO': 'colher'}, 32, 32, ['--cores', '12', '--ancora', 'centro', '--extra', '#5b5b5b,#898989,#b0b0b0,#c5c5c5']),
    'icone.galho': ('icone', {'TIPO': 'galho'}, 32, 32, ['--cores', '12', '--ancora', 'centro', '--extra', '#5b5b5b,#898989,#b0b0b0,#c5c5c5']),
    'icone.peixe': ('icone', {'TIPO': 'peixe'}, 32, 32, ['--cores', '12', '--ancora', 'centro', '--extra', '#5b5b5b,#898989,#b0b0b0,#c5c5c5']),
    'icone.saco': ('icone', {'TIPO': 'saco'}, 32, 32, ['--cores', '12', '--ancora', 'centro', '--extra', '#5b5b5b,#898989,#b0b0b0,#c5c5c5']),
    'icone.cueca': ('icone', {'TIPO': 'cueca'}, 32, 32, ['--cores', '12', '--ancora', 'centro', '--extra', '#5b5b5b,#898989,#b0b0b0,#c5c5c5']),
    'icone.balde': ('icone', {'TIPO': 'balde'}, 32, 32, ['--cores', '12', '--ancora', 'centro', '--extra', '#5b5b5b,#898989,#b0b0b0,#c5c5c5']),
    'icone.manto': ('icone', {'TIPO': 'manto'}, 32, 32, ['--cores', '12', '--ancora', 'centro', '--extra', '#5b5b5b,#898989,#b0b0b0,#c5c5c5']),
    'icone.peitoral': ('icone', {'TIPO': 'peitoral'}, 32, 32, ['--cores', '12', '--ancora', 'centro', '--extra', '#5b5b5b,#898989,#b0b0b0,#c5c5c5']),
    'icone.anel': ('icone', {'TIPO': 'anel'}, 32, 32, ['--cores', '12', '--ancora', 'centro', '--extra', '#5b5b5b,#898989,#b0b0b0,#c5c5c5']),
    'icone.pedra': ('icone', {'TIPO': 'pedra'}, 32, 32, ['--cores', '12', '--ancora', 'centro', '--extra', '#5b5b5b,#898989,#b0b0b0,#c5c5c5']),
    'icone.pena': ('icone', {'TIPO': 'pena'}, 32, 32, ['--cores', '12', '--ancora', 'centro', '--extra', '#5b5b5b,#898989,#b0b0b0,#c5c5c5']),
    'icone.coracao': ('icone', {'TIPO': 'coracao'}, 32, 32, ['--cores', '12', '--ancora', 'centro', '--extra', '#5b5b5b,#898989,#b0b0b0,#c5c5c5']),
    'icone.olho': ('icone', {'TIPO': 'olho'}, 32, 32, ['--cores', '12', '--ancora', 'centro', '--extra', '#5b5b5b,#898989,#b0b0b0,#c5c5c5']),
    'icone.amuleto': ('icone', {'TIPO': 'amuleto'}, 32, 32, ['--cores', '12', '--ancora', 'centro', '--extra', '#5b5b5b,#898989,#b0b0b0,#c5c5c5']),
    'ladrilho.0.chao0': ('ladrilho', {'TIPO': 'chao', 'ZONA': '0', 'VAR': '0'}, 32, 32, ['--fixo', '--cores', '10']),
    'ladrilho.0.chao1': ('ladrilho', {'TIPO': 'chao', 'ZONA': '0', 'VAR': '1'}, 32, 32, ['--fixo', '--cores', '10']),
    'ladrilho.0.chao2': ('ladrilho', {'TIPO': 'chao', 'ZONA': '0', 'VAR': '2'}, 32, 32, ['--fixo', '--cores', '10']),
    'ladrilho.0.chao3': ('ladrilho', {'TIPO': 'chao', 'ZONA': '0', 'VAR': '3'}, 32, 32, ['--fixo', '--cores', '10']),
    'ladrilho.0.face': ('ladrilho', {'TIPO': 'face', 'ZONA': '0'}, 32, 32, ['--fixo', '--cores', '10']),
    'ladrilho.0.faceAlt': ('ladrilho', {'TIPO': 'faceAlt', 'ZONA': '0'}, 32, 32, ['--fixo', '--cores', '10']),
    'ladrilho.0.topo': ('ladrilho', {'TIPO': 'topo', 'ZONA': '0'}, 32, 32, ['--fixo', '--cores', '10']),
    'ladrilho.1.chao0': ('ladrilho', {'TIPO': 'chao', 'ZONA': '1', 'VAR': '0'}, 32, 32, ['--fixo', '--cores', '10']),
    'ladrilho.1.chao1': ('ladrilho', {'TIPO': 'chao', 'ZONA': '1', 'VAR': '1'}, 32, 32, ['--fixo', '--cores', '10']),
    'ladrilho.1.chao2': ('ladrilho', {'TIPO': 'chao', 'ZONA': '1', 'VAR': '2'}, 32, 32, ['--fixo', '--cores', '10']),
    'ladrilho.1.chao3': ('ladrilho', {'TIPO': 'chao', 'ZONA': '1', 'VAR': '3'}, 32, 32, ['--fixo', '--cores', '10']),
    'ladrilho.1.face': ('ladrilho', {'TIPO': 'face', 'ZONA': '1'}, 32, 32, ['--fixo', '--cores', '10']),
    'ladrilho.1.faceAlt': ('ladrilho', {'TIPO': 'faceAlt', 'ZONA': '1'}, 32, 32, ['--fixo', '--cores', '10']),
    'ladrilho.1.topo': ('ladrilho', {'TIPO': 'topo', 'ZONA': '1'}, 32, 32, ['--fixo', '--cores', '10']),
    'ladrilho.2.chao0': ('ladrilho', {'TIPO': 'chao', 'ZONA': '2', 'VAR': '0'}, 32, 32, ['--fixo', '--cores', '10']),
    'ladrilho.2.chao1': ('ladrilho', {'TIPO': 'chao', 'ZONA': '2', 'VAR': '1'}, 32, 32, ['--fixo', '--cores', '10']),
    'ladrilho.2.chao2': ('ladrilho', {'TIPO': 'chao', 'ZONA': '2', 'VAR': '2'}, 32, 32, ['--fixo', '--cores', '10']),
    'ladrilho.2.chao3': ('ladrilho', {'TIPO': 'chao', 'ZONA': '2', 'VAR': '3'}, 32, 32, ['--fixo', '--cores', '10']),
    'ladrilho.2.face': ('ladrilho', {'TIPO': 'face', 'ZONA': '2'}, 32, 32, ['--fixo', '--cores', '10']),
    'ladrilho.2.faceAlt': ('ladrilho', {'TIPO': 'faceAlt', 'ZONA': '2'}, 32, 32, ['--fixo', '--cores', '10']),
    'ladrilho.2.topo': ('ladrilho', {'TIPO': 'topo', 'ZONA': '2'}, 32, 32, ['--fixo', '--cores', '10']),
    'ladrilho.3.chao0': ('ladrilho', {'TIPO': 'chao', 'ZONA': '3', 'VAR': '0'}, 32, 32, ['--fixo', '--cores', '10']),
    'ladrilho.3.chao1': ('ladrilho', {'TIPO': 'chao', 'ZONA': '3', 'VAR': '1'}, 32, 32, ['--fixo', '--cores', '10']),
    'ladrilho.3.chao2': ('ladrilho', {'TIPO': 'chao', 'ZONA': '3', 'VAR': '2'}, 32, 32, ['--fixo', '--cores', '10']),
    'ladrilho.3.chao3': ('ladrilho', {'TIPO': 'chao', 'ZONA': '3', 'VAR': '3'}, 32, 32, ['--fixo', '--cores', '10']),
    'ladrilho.3.face': ('ladrilho', {'TIPO': 'face', 'ZONA': '3'}, 32, 32, ['--fixo', '--cores', '10']),
    'ladrilho.3.faceAlt': ('ladrilho', {'TIPO': 'faceAlt', 'ZONA': '3'}, 32, 32, ['--fixo', '--cores', '10']),
    'ladrilho.3.topo': ('ladrilho', {'TIPO': 'topo', 'ZONA': '3'}, 32, 32, ['--fixo', '--cores', '10']),
    'ladrilho.4.chao0': ('ladrilho', {'TIPO': 'chao', 'ZONA': '4', 'VAR': '0'}, 32, 32, ['--fixo', '--cores', '10']),
    'ladrilho.4.chao1': ('ladrilho', {'TIPO': 'chao', 'ZONA': '4', 'VAR': '1'}, 32, 32, ['--fixo', '--cores', '10']),
    'ladrilho.4.chao2': ('ladrilho', {'TIPO': 'chao', 'ZONA': '4', 'VAR': '2'}, 32, 32, ['--fixo', '--cores', '10']),
    'ladrilho.4.chao3': ('ladrilho', {'TIPO': 'chao', 'ZONA': '4', 'VAR': '3'}, 32, 32, ['--fixo', '--cores', '10']),
    'ladrilho.4.face': ('ladrilho', {'TIPO': 'face', 'ZONA': '4'}, 32, 32, ['--fixo', '--cores', '10']),
    'ladrilho.4.faceAlt': ('ladrilho', {'TIPO': 'faceAlt', 'ZONA': '4'}, 32, 32, ['--fixo', '--cores', '10']),
    'ladrilho.4.topo': ('ladrilho', {'TIPO': 'topo', 'ZONA': '4'}, 32, 32, ['--fixo', '--cores', '10']),
    'ladrilho.5.chao0': ('ladrilho', {'TIPO': 'chao', 'ZONA': '5', 'VAR': '0'}, 32, 32, ['--fixo', '--cores', '10']),
    'ladrilho.5.chao1': ('ladrilho', {'TIPO': 'chao', 'ZONA': '5', 'VAR': '1'}, 32, 32, ['--fixo', '--cores', '10']),
    'ladrilho.5.chao2': ('ladrilho', {'TIPO': 'chao', 'ZONA': '5', 'VAR': '2'}, 32, 32, ['--fixo', '--cores', '10']),
    'ladrilho.5.chao3': ('ladrilho', {'TIPO': 'chao', 'ZONA': '5', 'VAR': '3'}, 32, 32, ['--fixo', '--cores', '10']),
    'ladrilho.5.face': ('ladrilho', {'TIPO': 'face', 'ZONA': '5'}, 32, 32, ['--fixo', '--cores', '10']),
    'ladrilho.5.faceAlt': ('ladrilho', {'TIPO': 'faceAlt', 'ZONA': '5'}, 32, 32, ['--fixo', '--cores', '10']),
    'ladrilho.5.topo': ('ladrilho', {'TIPO': 'topo', 'ZONA': '5'}, 32, 32, ['--fixo', '--cores', '10']),
    'ladrilho.6.chao0': ('ladrilho', {'TIPO': 'chao', 'ZONA': '6', 'VAR': '0'}, 32, 32, ['--fixo', '--cores', '10']),
    'ladrilho.6.chao1': ('ladrilho', {'TIPO': 'chao', 'ZONA': '6', 'VAR': '1'}, 32, 32, ['--fixo', '--cores', '10']),
    'ladrilho.6.chao2': ('ladrilho', {'TIPO': 'chao', 'ZONA': '6', 'VAR': '2'}, 32, 32, ['--fixo', '--cores', '10']),
    'ladrilho.6.chao3': ('ladrilho', {'TIPO': 'chao', 'ZONA': '6', 'VAR': '3'}, 32, 32, ['--fixo', '--cores', '10']),
    'ladrilho.6.face': ('ladrilho', {'TIPO': 'face', 'ZONA': '6'}, 32, 32, ['--fixo', '--cores', '10']),
    'ladrilho.6.faceAlt': ('ladrilho', {'TIPO': 'faceAlt', 'ZONA': '6'}, 32, 32, ['--fixo', '--cores', '10']),
    'ladrilho.6.topo': ('ladrilho', {'TIPO': 'topo', 'ZONA': '6'}, 32, 32, ['--fixo', '--cores', '10']),
    'ladrilho.7.chao0': ('ladrilho', {'TIPO': 'chao', 'ZONA': '7', 'VAR': '0'}, 32, 32, ['--fixo', '--cores', '10']),
    'ladrilho.7.chao1': ('ladrilho', {'TIPO': 'chao', 'ZONA': '7', 'VAR': '1'}, 32, 32, ['--fixo', '--cores', '10']),
    'ladrilho.7.chao2': ('ladrilho', {'TIPO': 'chao', 'ZONA': '7', 'VAR': '2'}, 32, 32, ['--fixo', '--cores', '10']),
    'ladrilho.7.chao3': ('ladrilho', {'TIPO': 'chao', 'ZONA': '7', 'VAR': '3'}, 32, 32, ['--fixo', '--cores', '10']),
    'ladrilho.7.face': ('ladrilho', {'TIPO': 'face', 'ZONA': '7'}, 32, 32, ['--fixo', '--cores', '10']),
    'ladrilho.7.faceAlt': ('ladrilho', {'TIPO': 'faceAlt', 'ZONA': '7'}, 32, 32, ['--fixo', '--cores', '10']),
    'ladrilho.7.topo': ('ladrilho', {'TIPO': 'topo', 'ZONA': '7'}, 32, 32, ['--fixo', '--cores', '10']),
    'ladrilho.8.chao0': ('ladrilho', {'TIPO': 'chao', 'ZONA': '8', 'VAR': '0'}, 32, 32, ['--fixo', '--cores', '10']),
    'ladrilho.8.chao1': ('ladrilho', {'TIPO': 'chao', 'ZONA': '8', 'VAR': '1'}, 32, 32, ['--fixo', '--cores', '10']),
    'ladrilho.8.chao2': ('ladrilho', {'TIPO': 'chao', 'ZONA': '8', 'VAR': '2'}, 32, 32, ['--fixo', '--cores', '10']),
    'ladrilho.8.chao3': ('ladrilho', {'TIPO': 'chao', 'ZONA': '8', 'VAR': '3'}, 32, 32, ['--fixo', '--cores', '10']),
    'ladrilho.8.face': ('ladrilho', {'TIPO': 'face', 'ZONA': '8'}, 32, 32, ['--fixo', '--cores', '10']),
    'ladrilho.8.faceAlt': ('ladrilho', {'TIPO': 'faceAlt', 'ZONA': '8'}, 32, 32, ['--fixo', '--cores', '10']),
    'ladrilho.8.topo': ('ladrilho', {'TIPO': 'topo', 'ZONA': '8'}, 32, 32, ['--fixo', '--cores', '10']),
    'ladrilho.9.chao0': ('ladrilho', {'TIPO': 'chao', 'ZONA': '9', 'VAR': '0'}, 32, 32, ['--fixo', '--cores', '10']),
    'ladrilho.9.chao1': ('ladrilho', {'TIPO': 'chao', 'ZONA': '9', 'VAR': '1'}, 32, 32, ['--fixo', '--cores', '10']),
    'ladrilho.9.chao2': ('ladrilho', {'TIPO': 'chao', 'ZONA': '9', 'VAR': '2'}, 32, 32, ['--fixo', '--cores', '10']),
    'ladrilho.9.chao3': ('ladrilho', {'TIPO': 'chao', 'ZONA': '9', 'VAR': '3'}, 32, 32, ['--fixo', '--cores', '10']),
    'ladrilho.9.face': ('ladrilho', {'TIPO': 'face', 'ZONA': '9'}, 32, 32, ['--fixo', '--cores', '10']),
    'ladrilho.9.faceAlt': ('ladrilho', {'TIPO': 'faceAlt', 'ZONA': '9'}, 32, 32, ['--fixo', '--cores', '10']),
    'ladrilho.9.topo': ('ladrilho', {'TIPO': 'topo', 'ZONA': '9'}, 32, 32, ['--fixo', '--cores', '10']),
    'heroi.azul': ('heroi_skin', {'SKIN': 'azul'}, 32, 32, ['--quadro', '--ordem', 'parado-baixo,parado-direita,parado-cima,anda-baixo,anda-direita,anda-cima,ataque-baixo,ataque-direita,ataque-cima', '--cores', '16', '--extra', '#8f008f,#c700c7,#ff00ff,#008f8f,#00c7c7,#00ffff']),
    'heroi.carmesim': ('heroi_skin', {'SKIN': 'carmesim'}, 32, 32, ['--quadro', '--ordem', 'parado-baixo,parado-direita,parado-cima,anda-baixo,anda-direita,anda-cima,ataque-baixo,ataque-direita,ataque-cima', '--cores', '16', '--extra', '#8f008f,#c700c7,#ff00ff,#008f8f,#00c7c7,#00ffff']),
    'heroi.floresta': ('heroi_skin', {'SKIN': 'floresta'}, 32, 32, ['--quadro', '--ordem', 'parado-baixo,parado-direita,parado-cima,anda-baixo,anda-direita,anda-cima,ataque-baixo,ataque-direita,ataque-cima', '--cores', '16', '--extra', '#8f008f,#c700c7,#ff00ff,#008f8f,#00c7c7,#00ffff']),
    'heroi.sombra': ('heroi_skin', {'SKIN': 'sombra'}, 32, 32, ['--quadro', '--ordem', 'parado-baixo,parado-direita,parado-cima,anda-baixo,anda-direita,anda-cima,ataque-baixo,ataque-direita,ataque-cima', '--cores', '16', '--extra', '#8f008f,#c700c7,#ff00ff,#008f8f,#00c7c7,#00ffff']),
    'heroi.real': ('heroi_skin', {'SKIN': 'real'}, 32, 32, ['--quadro', '--ordem', 'parado-baixo,parado-direita,parado-cima,anda-baixo,anda-direita,anda-cima,ataque-baixo,ataque-direita,ataque-cima', '--cores', '16', '--extra', '#8f008f,#c700c7,#ff00ff,#008f8f,#00c7c7,#00ffff']),
    'heroi.gelo': ('heroi_skin', {'SKIN': 'gelo'}, 32, 32, ['--quadro', '--ordem', 'parado-baixo,parado-direita,parado-cima,anda-baixo,anda-direita,anda-cima,ataque-baixo,ataque-direita,ataque-cima', '--cores', '16', '--extra', '#8f008f,#c700c7,#ff00ff,#008f8f,#00c7c7,#00ffff']),
    'heroi.dourado': ('heroi_skin', {'SKIN': 'dourado'}, 32, 32, ['--quadro', '--ordem', 'parado-baixo,parado-direita,parado-cima,anda-baixo,anda-direita,anda-cima,ataque-baixo,ataque-direita,ataque-cima', '--cores', '16', '--extra', '#8f008f,#c700c7,#ff00ff,#008f8f,#00c7c7,#00ffff']),
    'heroi.infinito': ('heroi_skin', {'SKIN': 'infinito'}, 32, 32, ['--quadro', '--ordem', 'parado-baixo,parado-direita,parado-cima,anda-baixo,anda-direita,anda-cima,ataque-baixo,ataque-direita,ataque-cima', '--cores', '16', '--extra', '#8f008f,#c700c7,#ff00ff,#008f8f,#00c7c7,#00ffff']),
    'heroi.celestial': ('heroi_skin', {'SKIN': 'celestial'}, 32, 32, ['--quadro', '--ordem', 'parado-baixo,parado-direita,parado-cima,anda-baixo,anda-direita,anda-cima,ataque-baixo,ataque-direita,ataque-cima', '--cores', '16', '--extra', '#8f008f,#c700c7,#ff00ff,#008f8f,#00c7c7,#00ffff']),
    'heroi.draconica': ('heroi_skin', {'SKIN': 'draconica'}, 32, 32, ['--quadro', '--ordem', 'parado-baixo,parado-direita,parado-cima,anda-baixo,anda-direita,anda-cima,ataque-baixo,ataque-direita,ataque-cima', '--cores', '16', '--extra', '#8f008f,#c700c7,#ff00ff,#008f8f,#00c7c7,#00ffff']),
    'heroi.infernal': ('heroi_skin', {'SKIN': 'infernal'}, 32, 32, ['--quadro', '--ordem', 'parado-baixo,parado-direita,parado-cima,anda-baixo,anda-direita,anda-cima,ataque-baixo,ataque-direita,ataque-cima', '--cores', '16', '--extra', '#8f008f,#c700c7,#ff00ff,#008f8f,#00c7c7,#00ffff']),
    'heroi.cristal': ('heroi_skin', {'SKIN': 'cristal'}, 32, 32, ['--quadro', '--ordem', 'parado-baixo,parado-direita,parado-cima,anda-baixo,anda-direita,anda-cima,ataque-baixo,ataque-direita,ataque-cima', '--cores', '16', '--extra', '#8f008f,#c700c7,#ff00ff,#008f8f,#00c7c7,#00ffff']),
    'heroi.vazio': ('heroi_skin', {'SKIN': 'vazio'}, 32, 32, ['--quadro', '--ordem', 'parado-baixo,parado-direita,parado-cima,anda-baixo,anda-direita,anda-cima,ataque-baixo,ataque-direita,ataque-cima', '--cores', '16', '--extra', '#8f008f,#c700c7,#ff00ff,#008f8f,#00c7c7,#00ffff']),
    'heroi.lendaria': ('heroi_skin', {'SKIN': 'lendaria'}, 32, 32, ['--quadro', '--ordem', 'parado-baixo,parado-direita,parado-cima,anda-baixo,anda-direita,anda-cima,ataque-baixo,ataque-direita,ataque-cima', '--cores', '16', '--extra', '#8f008f,#c700c7,#ff00ff,#008f8f,#00c7c7,#00ffff']),
    'heroi.magma': ('heroi_skin', {'SKIN': 'magma'}, 32, 32, ['--quadro', '--ordem', 'parado-baixo,parado-direita,parado-cima,anda-baixo,anda-direita,anda-cima,ataque-baixo,ataque-direita,ataque-cima', '--cores', '16', '--extra', '#8f008f,#c700c7,#ff00ff,#008f8f,#00c7c7,#00ffff']),
    'raca.elfo': ('heroi_skin', {'SKIN': 'azul', 'RACA': 'elfo'}, 32, 32, ['--quadro', '--ordem', 'parado-baixo,parado-direita,parado-cima,anda-baixo,anda-direita,anda-cima,ataque-baixo,ataque-direita,ataque-cima', '--cores', '10', '--extra', '#8f008f,#c700c7,#ff00ff,#008f8f,#00c7c7,#00ffff']),
    'raca.anao': ('heroi_skin', {'SKIN': 'azul', 'RACA': 'anao'}, 32, 32, ['--quadro', '--ordem', 'parado-baixo,parado-direita,parado-cima,anda-baixo,anda-direita,anda-cima,ataque-baixo,ataque-direita,ataque-cima', '--cores', '10', '--extra', '#8f008f,#c700c7,#ff00ff,#008f8f,#00c7c7,#00ffff']),
    'raca.orc': ('heroi_skin', {'SKIN': 'azul', 'RACA': 'orc'}, 32, 32, ['--quadro', '--ordem', 'parado-baixo,parado-direita,parado-cima,anda-baixo,anda-direita,anda-cima,ataque-baixo,ataque-direita,ataque-cima', '--cores', '10', '--extra', '#8f008f,#c700c7,#ff00ff,#008f8f,#00c7c7,#00ffff']),
    'raca.vampiro': ('heroi_skin', {'SKIN': 'azul', 'RACA': 'vampiro'}, 32, 32, ['--quadro', '--ordem', 'parado-baixo,parado-direita,parado-cima,anda-baixo,anda-direita,anda-cima,ataque-baixo,ataque-direita,ataque-cima', '--cores', '10', '--extra', '#8f008f,#c700c7,#ff00ff,#008f8f,#00c7c7,#00ffff']),
    'raca.gnomo': ('heroi_skin', {'SKIN': 'azul', 'RACA': 'gnomo'}, 32, 32, ['--quadro', '--ordem', 'parado-baixo,parado-direita,parado-cima,anda-baixo,anda-direita,anda-cima,ataque-baixo,ataque-direita,ataque-cima', '--cores', '10', '--extra', '#8f008f,#c700c7,#ff00ff,#008f8f,#00c7c7,#00ffff']),
    'raca.draconato': ('heroi_skin', {'SKIN': 'azul', 'RACA': 'draconato'}, 32, 32, ['--quadro', '--ordem', 'parado-baixo,parado-direita,parado-cima,anda-baixo,anda-direita,anda-cima,ataque-baixo,ataque-direita,ataque-cima', '--cores', '10', '--extra', '#8f008f,#c700c7,#ff00ff,#008f8f,#00c7c7,#00ffff']),
    'raca.mortoVivo': ('heroi_skin', {'SKIN': 'azul', 'RACA': 'mortoVivo'}, 32, 32, ['--quadro', '--ordem', 'parado-baixo,parado-direita,parado-cima,anda-baixo,anda-direita,anda-cima,ataque-baixo,ataque-direita,ataque-cima', '--cores', '10', '--extra', '#8f008f,#c700c7,#ff00ff,#008f8f,#00c7c7,#00ffff']),
    'raca.anjo': ('heroi_skin', {'SKIN': 'azul', 'RACA': 'anjo'}, 32, 32, ['--quadro', '--ordem', 'parado-baixo,parado-direita,parado-cima,anda-baixo,anda-direita,anda-cima,ataque-baixo,ataque-direita,ataque-cima', '--cores', '10', '--extra', '#8f008f,#c700c7,#ff00ff,#008f8f,#00c7c7,#00ffff']),
    'raca.demonio': ('heroi_skin', {'SKIN': 'azul', 'RACA': 'demonio'}, 32, 32, ['--quadro', '--ordem', 'parado-baixo,parado-direita,parado-cima,anda-baixo,anda-direita,anda-cima,ataque-baixo,ataque-direita,ataque-cima', '--cores', '10', '--extra', '#8f008f,#c700c7,#ff00ff,#008f8f,#00c7c7,#00ffff']),
    'raca.lagarto': ('heroi_skin', {'SKIN': 'azul', 'RACA': 'lagarto'}, 32, 32, ['--quadro', '--ordem', 'parado-baixo,parado-direita,parado-cima,anda-baixo,anda-direita,anda-cima,ataque-baixo,ataque-direita,ataque-cima', '--cores', '10', '--extra', '#8f008f,#c700c7,#ff00ff,#008f8f,#00c7c7,#00ffff']),
    'edificio.casa': ('cidade', {'TIPO': 'casa'}, 208, 200, ['--quadro', '--cores', '20']),
    'edificio.assoc': ('cidade', {'TIPO': 'assoc'}, 208, 200, ['--quadro', '--cores', '20']),
    'edificio.ferreiro': ('cidade', {'TIPO': 'ferreiro'}, 208, 200, ['--quadro', '--cores', '20']),
    'edificio.alquimista': ('cidade', {'TIPO': 'alquimista'}, 208, 200, ['--quadro', '--cores', '20']),
    'cidade.0.fonte': ('cidade', {'TIPO': 'fonte', 'TEMA': '0'}, 92, 70, ['--quadro', '--cores', '14']),
    'cidade.0.candeeiro': ('cidade', {'TIPO': 'candeeiro', 'TEMA': '0'}, 14, 52, ['--quadro', '--cores', '8']),
    'cidade.1.fonte': ('cidade', {'TIPO': 'fonte', 'TEMA': '1'}, 92, 70, ['--quadro', '--cores', '14']),
    'cidade.1.candeeiro': ('cidade', {'TIPO': 'candeeiro', 'TEMA': '1'}, 14, 52, ['--quadro', '--cores', '8']),
    'cidade.2.fonte': ('cidade', {'TIPO': 'fonte', 'TEMA': '2'}, 92, 70, ['--quadro', '--cores', '14']),
    'cidade.2.candeeiro': ('cidade', {'TIPO': 'candeeiro', 'TEMA': '2'}, 14, 52, ['--quadro', '--cores', '8']),
    'cidade.3.fonte': ('cidade', {'TIPO': 'fonte', 'TEMA': '3'}, 92, 70, ['--quadro', '--cores', '14']),
    'cidade.3.candeeiro': ('cidade', {'TIPO': 'candeeiro', 'TEMA': '3'}, 14, 52, ['--quadro', '--cores', '8']),
    'cidade.4.fonte': ('cidade', {'TIPO': 'fonte', 'TEMA': '4'}, 92, 70, ['--quadro', '--cores', '14']),
    'cidade.4.candeeiro': ('cidade', {'TIPO': 'candeeiro', 'TEMA': '4'}, 14, 52, ['--quadro', '--cores', '8']),
    'cidade.5.fonte': ('cidade', {'TIPO': 'fonte', 'TEMA': '5'}, 92, 70, ['--quadro', '--cores', '14']),
    'cidade.5.candeeiro': ('cidade', {'TIPO': 'candeeiro', 'TEMA': '5'}, 14, 52, ['--quadro', '--cores', '8']),
    'cidade.6.fonte': ('cidade', {'TIPO': 'fonte', 'TEMA': '6'}, 92, 70, ['--quadro', '--cores', '14']),
    'cidade.6.candeeiro': ('cidade', {'TIPO': 'candeeiro', 'TEMA': '6'}, 14, 52, ['--quadro', '--cores', '8']),
    'cidade.7.fonte': ('cidade', {'TIPO': 'fonte', 'TEMA': '7'}, 92, 70, ['--quadro', '--cores', '14']),
    'cidade.7.candeeiro': ('cidade', {'TIPO': 'candeeiro', 'TEMA': '7'}, 14, 52, ['--quadro', '--cores', '8']),
    'cidade.8.fonte': ('cidade', {'TIPO': 'fonte', 'TEMA': '8'}, 92, 70, ['--quadro', '--cores', '14']),
    'cidade.8.candeeiro': ('cidade', {'TIPO': 'candeeiro', 'TEMA': '8'}, 14, 52, ['--quadro', '--cores', '8']),
    'cidade.9.fonte': ('cidade', {'TIPO': 'fonte', 'TEMA': '9'}, 92, 70, ['--quadro', '--cores', '14']),
    'cidade.9.candeeiro': ('cidade', {'TIPO': 'candeeiro', 'TEMA': '9'}, 14, 52, ['--quadro', '--cores', '8']),
    'arvores.pinheiro': ('cidade', {'TIPO': 'arv_pinheiro'}, 34, 36, ['--cores', '12']),
    'arvores.morta': ('cidade', {'TIPO': 'arv_morta'}, 34, 32, ['--cores', '12']),
    'arvores.rocha': ('cidade', {'TIPO': 'arv_rocha'}, 34, 24, ['--cores', '12']),
    'arvores.salgueiro': ('cidade', {'TIPO': 'arv_salgueiro'}, 34, 26, ['--cores', '12']),
    'arvores.palmeira': ('cidade', {'TIPO': 'arv_palmeira'}, 34, 32, ['--cores', '12']),
    'arvores.cristal': ('cidade', {'TIPO': 'arv_cristal'}, 34, 28, ['--cores', '12']),
    'arvores.obelisco': ('cidade', {'TIPO': 'arv_obelisco'}, 34, 30, ['--cores', '12']),
    'arvores.coluna': ('cidade', {'TIPO': 'arv_coluna'}, 34, 30, ['--cores', '12']),
    'arvores.ruina': ('cidade', {'TIPO': 'arv_ruina'}, 34, 24, ['--cores', '12']),
    'arvores.arvore': ('cidade', {'TIPO': 'arv_arvore'}, 34, 30, ['--cores', '12']),
    'cidade.0.relva0': ('chao_cidade', {'TIPO': 'relva0', 'TEMA': '0'}, 32, 32, ['--fixo', '--cores', '10']),
    'cidade.0.relva1': ('chao_cidade', {'TIPO': 'relva1', 'TEMA': '0'}, 32, 32, ['--fixo', '--cores', '10']),
    'cidade.0.relva2': ('chao_cidade', {'TIPO': 'relva2', 'TEMA': '0'}, 32, 32, ['--fixo', '--cores', '10']),
    'cidade.0.calc0': ('chao_cidade', {'TIPO': 'calc0', 'TEMA': '0'}, 32, 32, ['--fixo', '--cores', '10']),
    'cidade.0.calc1': ('chao_cidade', {'TIPO': 'calc1', 'TEMA': '0'}, 32, 32, ['--fixo', '--cores', '10']),
    'cidade.0.muralha': ('chao_cidade', {'TIPO': 'muralha', 'TEMA': '0'}, 32, 32, ['--fixo', '--cores', '10']),
    'cidade.1.relva0': ('chao_cidade', {'TIPO': 'relva0', 'TEMA': '1'}, 32, 32, ['--fixo', '--cores', '10']),
    'cidade.1.relva1': ('chao_cidade', {'TIPO': 'relva1', 'TEMA': '1'}, 32, 32, ['--fixo', '--cores', '10']),
    'cidade.1.relva2': ('chao_cidade', {'TIPO': 'relva2', 'TEMA': '1'}, 32, 32, ['--fixo', '--cores', '10']),
    'cidade.1.calc0': ('chao_cidade', {'TIPO': 'calc0', 'TEMA': '1'}, 32, 32, ['--fixo', '--cores', '10']),
    'cidade.1.calc1': ('chao_cidade', {'TIPO': 'calc1', 'TEMA': '1'}, 32, 32, ['--fixo', '--cores', '10']),
    'cidade.1.muralha': ('chao_cidade', {'TIPO': 'muralha', 'TEMA': '1'}, 32, 32, ['--fixo', '--cores', '10']),
    'cidade.2.relva0': ('chao_cidade', {'TIPO': 'relva0', 'TEMA': '2'}, 32, 32, ['--fixo', '--cores', '10']),
    'cidade.2.relva1': ('chao_cidade', {'TIPO': 'relva1', 'TEMA': '2'}, 32, 32, ['--fixo', '--cores', '10']),
    'cidade.2.relva2': ('chao_cidade', {'TIPO': 'relva2', 'TEMA': '2'}, 32, 32, ['--fixo', '--cores', '10']),
    'cidade.2.calc0': ('chao_cidade', {'TIPO': 'calc0', 'TEMA': '2'}, 32, 32, ['--fixo', '--cores', '10']),
    'cidade.2.calc1': ('chao_cidade', {'TIPO': 'calc1', 'TEMA': '2'}, 32, 32, ['--fixo', '--cores', '10']),
    'cidade.2.muralha': ('chao_cidade', {'TIPO': 'muralha', 'TEMA': '2'}, 32, 32, ['--fixo', '--cores', '10']),
    'cidade.3.relva0': ('chao_cidade', {'TIPO': 'relva0', 'TEMA': '3'}, 32, 32, ['--fixo', '--cores', '10']),
    'cidade.3.relva1': ('chao_cidade', {'TIPO': 'relva1', 'TEMA': '3'}, 32, 32, ['--fixo', '--cores', '10']),
    'cidade.3.relva2': ('chao_cidade', {'TIPO': 'relva2', 'TEMA': '3'}, 32, 32, ['--fixo', '--cores', '10']),
    'cidade.3.calc0': ('chao_cidade', {'TIPO': 'calc0', 'TEMA': '3'}, 32, 32, ['--fixo', '--cores', '10']),
    'cidade.3.calc1': ('chao_cidade', {'TIPO': 'calc1', 'TEMA': '3'}, 32, 32, ['--fixo', '--cores', '10']),
    'cidade.3.muralha': ('chao_cidade', {'TIPO': 'muralha', 'TEMA': '3'}, 32, 32, ['--fixo', '--cores', '10']),
    'cidade.4.relva0': ('chao_cidade', {'TIPO': 'relva0', 'TEMA': '4'}, 32, 32, ['--fixo', '--cores', '10']),
    'cidade.4.relva1': ('chao_cidade', {'TIPO': 'relva1', 'TEMA': '4'}, 32, 32, ['--fixo', '--cores', '10']),
    'cidade.4.relva2': ('chao_cidade', {'TIPO': 'relva2', 'TEMA': '4'}, 32, 32, ['--fixo', '--cores', '10']),
    'cidade.4.calc0': ('chao_cidade', {'TIPO': 'calc0', 'TEMA': '4'}, 32, 32, ['--fixo', '--cores', '10']),
    'cidade.4.calc1': ('chao_cidade', {'TIPO': 'calc1', 'TEMA': '4'}, 32, 32, ['--fixo', '--cores', '10']),
    'cidade.4.muralha': ('chao_cidade', {'TIPO': 'muralha', 'TEMA': '4'}, 32, 32, ['--fixo', '--cores', '10']),
    'cidade.5.relva0': ('chao_cidade', {'TIPO': 'relva0', 'TEMA': '5'}, 32, 32, ['--fixo', '--cores', '10']),
    'cidade.5.relva1': ('chao_cidade', {'TIPO': 'relva1', 'TEMA': '5'}, 32, 32, ['--fixo', '--cores', '10']),
    'cidade.5.relva2': ('chao_cidade', {'TIPO': 'relva2', 'TEMA': '5'}, 32, 32, ['--fixo', '--cores', '10']),
    'cidade.5.calc0': ('chao_cidade', {'TIPO': 'calc0', 'TEMA': '5'}, 32, 32, ['--fixo', '--cores', '10']),
    'cidade.5.calc1': ('chao_cidade', {'TIPO': 'calc1', 'TEMA': '5'}, 32, 32, ['--fixo', '--cores', '10']),
    'cidade.5.muralha': ('chao_cidade', {'TIPO': 'muralha', 'TEMA': '5'}, 32, 32, ['--fixo', '--cores', '10']),
    'cidade.6.relva0': ('chao_cidade', {'TIPO': 'relva0', 'TEMA': '6'}, 32, 32, ['--fixo', '--cores', '10']),
    'cidade.6.relva1': ('chao_cidade', {'TIPO': 'relva1', 'TEMA': '6'}, 32, 32, ['--fixo', '--cores', '10']),
    'cidade.6.relva2': ('chao_cidade', {'TIPO': 'relva2', 'TEMA': '6'}, 32, 32, ['--fixo', '--cores', '10']),
    'cidade.6.calc0': ('chao_cidade', {'TIPO': 'calc0', 'TEMA': '6'}, 32, 32, ['--fixo', '--cores', '10']),
    'cidade.6.calc1': ('chao_cidade', {'TIPO': 'calc1', 'TEMA': '6'}, 32, 32, ['--fixo', '--cores', '10']),
    'cidade.6.muralha': ('chao_cidade', {'TIPO': 'muralha', 'TEMA': '6'}, 32, 32, ['--fixo', '--cores', '10']),
    'cidade.7.relva0': ('chao_cidade', {'TIPO': 'relva0', 'TEMA': '7'}, 32, 32, ['--fixo', '--cores', '10']),
    'cidade.7.relva1': ('chao_cidade', {'TIPO': 'relva1', 'TEMA': '7'}, 32, 32, ['--fixo', '--cores', '10']),
    'cidade.7.relva2': ('chao_cidade', {'TIPO': 'relva2', 'TEMA': '7'}, 32, 32, ['--fixo', '--cores', '10']),
    'cidade.7.calc0': ('chao_cidade', {'TIPO': 'calc0', 'TEMA': '7'}, 32, 32, ['--fixo', '--cores', '10']),
    'cidade.7.calc1': ('chao_cidade', {'TIPO': 'calc1', 'TEMA': '7'}, 32, 32, ['--fixo', '--cores', '10']),
    'cidade.7.muralha': ('chao_cidade', {'TIPO': 'muralha', 'TEMA': '7'}, 32, 32, ['--fixo', '--cores', '10']),
    'cidade.8.relva0': ('chao_cidade', {'TIPO': 'relva0', 'TEMA': '8'}, 32, 32, ['--fixo', '--cores', '10']),
    'cidade.8.relva1': ('chao_cidade', {'TIPO': 'relva1', 'TEMA': '8'}, 32, 32, ['--fixo', '--cores', '10']),
    'cidade.8.relva2': ('chao_cidade', {'TIPO': 'relva2', 'TEMA': '8'}, 32, 32, ['--fixo', '--cores', '10']),
    'cidade.8.calc0': ('chao_cidade', {'TIPO': 'calc0', 'TEMA': '8'}, 32, 32, ['--fixo', '--cores', '10']),
    'cidade.8.calc1': ('chao_cidade', {'TIPO': 'calc1', 'TEMA': '8'}, 32, 32, ['--fixo', '--cores', '10']),
    'cidade.8.muralha': ('chao_cidade', {'TIPO': 'muralha', 'TEMA': '8'}, 32, 32, ['--fixo', '--cores', '10']),
    'cidade.9.relva0': ('chao_cidade', {'TIPO': 'relva0', 'TEMA': '9'}, 32, 32, ['--fixo', '--cores', '10']),
    'cidade.9.relva1': ('chao_cidade', {'TIPO': 'relva1', 'TEMA': '9'}, 32, 32, ['--fixo', '--cores', '10']),
    'cidade.9.relva2': ('chao_cidade', {'TIPO': 'relva2', 'TEMA': '9'}, 32, 32, ['--fixo', '--cores', '10']),
    'cidade.9.calc0': ('chao_cidade', {'TIPO': 'calc0', 'TEMA': '9'}, 32, 32, ['--fixo', '--cores', '10']),
    'cidade.9.calc1': ('chao_cidade', {'TIPO': 'calc1', 'TEMA': '9'}, 32, 32, ['--fixo', '--cores', '10']),
    'cidade.9.muralha': ('chao_cidade', {'TIPO': 'muralha', 'TEMA': '9'}, 32, 32, ['--fixo', '--cores', '10']),
    'art.alavanca.0': ('extras', {'TIPO': 'alavanca', 'VAR': '0'}, 24, 24, ['--caixa', '2,0,22,24', '--cores', '12']),
    'art.alavanca.1': ('extras', {'TIPO': 'alavanca', 'VAR': '1'}, 24, 24, ['--caixa', '0,0,22,24', '--cores', '12']),
    'art.placa.0': ('extras', {'TIPO': 'placa', 'VAR': '0'}, 28, 28, ['--caixa', '0,0,28,28', '--cores', '12']),
    'art.placa.1': ('extras', {'TIPO': 'placa', 'VAR': '1'}, 28, 28, ['--caixa', '0,0,28,28', '--cores', '12']),
    'art.pedra.0': ('extras', {'TIPO': 'pedra', 'VAR': '0'}, 28, 38, ['--caixa', '0,0,28,38', '--cores', '12']),
    'art.pedra.1': ('extras', {'TIPO': 'pedra', 'VAR': '1'}, 28, 38, ['--caixa', '0,0,28,38', '--cores', '12']),
    'art.duende': ('extras', {'TIPO': 'duende'}, 32, 32, ['--caixa', '0,2,32,30', '--cores', '12']),
    'art.jaula': ('extras', {'TIPO': 'jaula'}, 40, 32, ['--caixa', '0,0,40,32', '--cores', '12']),
    'art.arena': ('extras', {'TIPO': 'arena'}, 60, 44, ['--caixa', '0,0,60,44', '--cores', '12']),
    'art.lago': ('extras', {'TIPO': 'lago'}, 64, 28, ['--caixa', '0,0,64,28', '--cores', '12']),
    'art.cais': ('extras', {'TIPO': 'cais'}, 46, 32, ['--caixa', '0,0,46,32', '--cores', '12']),
    'art.grelhaGas': ('extras', {'TIPO': 'grelhaGas'}, 24, 20, ['--caixa', '0,0,24,20', '--cores', '12']),
    'art.estatua.0.frente': ('extras', {'TIPO': 'estatua', 'VAR': '0', 'COR': 'frente'}, 24, 30, ['--caixa', '0,0,24,30', '--cores', '12']),
    'art.estatua.0.costas': ('extras', {'TIPO': 'estatua', 'VAR': '0', 'COR': 'costas'}, 24, 30, ['--caixa', '0,0,24,30', '--cores', '12']),
    'art.estatua.0.lado': ('extras', {'TIPO': 'estatua', 'VAR': '0', 'COR': 'lado'}, 24, 30, ['--caixa', '0,0,24,30', '--cores', '12']),
    'art.estatua.1.frente': ('extras', {'TIPO': 'estatua', 'VAR': '1', 'COR': 'frente'}, 24, 30, ['--caixa', '0,0,24,30', '--cores', '12']),
    'art.estatua.1.costas': ('extras', {'TIPO': 'estatua', 'VAR': '1', 'COR': 'costas'}, 24, 30, ['--caixa', '0,0,24,30', '--cores', '12']),
    'art.estatua.1.lado': ('extras', {'TIPO': 'estatua', 'VAR': '1', 'COR': 'lado'}, 24, 30, ['--caixa', '0,0,24,30', '--cores', '12']),
    'art.sapos.0': ('extras', {'TIPO': 'sapo', 'COR': '0'}, 28, 20, ['--caixa', '0,0,28,20', '--cores', '12']),
    'art.sapos.1': ('extras', {'TIPO': 'sapo', 'COR': '1'}, 28, 20, ['--caixa', '0,0,28,20', '--cores', '12']),
    'art.sapos.2': ('extras', {'TIPO': 'sapo', 'COR': '2'}, 28, 20, ['--caixa', '0,0,28,20', '--cores', '12']),
    'art.moveis.cama': ('extras', {'TIPO': 'cama'}, 36, 20, ['--caixa', '0,0,36,20', '--cores', '12']),
    'art.moveis.tapete': ('extras', {'TIPO': 'tapete'}, 40, 18, ['--caixa', '0,0,40,18', '--cores', '12']),
    'art.moveis.planta': ('extras', {'TIPO': 'planta'}, 24, 24, ['--caixa', '2,0,20,24', '--cores', '12']),
    'art.moveis.estante': ('extras', {'TIPO': 'estante'}, 32, 28, ['--caixa', '0,0,32,28', '--cores', '12']),
    'art.moveis.lareira': ('extras', {'TIPO': 'lareira'}, 32, 24, ['--caixa', '0,0,32,24', '--cores', '12']),
    'art.moveis.armas': ('extras', {'TIPO': 'armas'}, 32, 24, ['--caixa', '0,0,32,24', '--cores', '12']),
    'art.moveis.quadro': ('extras', {'TIPO': 'quadro'}, 28, 24, ['--caixa', '0,0,28,24', '--cores', '12']),
    'art.moveis.aquario': ('extras', {'TIPO': 'aquario'}, 36, 26, ['--caixa', '0,0,36,26', '--cores', '12']),
    'art.peixes.Peixe Prateado': ('extras', {'TIPO': 'peixe', 'COR': 'prateado'}, 28, 16, ['--caixa', '0,0,28,16', '--cores', '12']),
    'art.peixes.Peixe Dourado': ('extras', {'TIPO': 'peixe', 'COR': 'dourado'}, 28, 16, ['--caixa', '0,0,28,16', '--cores', '12']),
    'art.peixes.Garrafa com Poção': ('extras', {'TIPO': 'garrafa'}, 20, 18, ['--caixa', '2,0,16,18', '--cores', '12']),
    'art.peixes.Bota Velha': ('extras', {'TIPO': 'bota'}, 22, 18, ['--caixa', '0,0,22,18', '--cores', '12']),
}


def fazer(nome):
    modelo, env, w, h, op = LISTA[nome]
    pasta = os.path.join(AQUI, 'render', nome)
    e = dict(os.environ, **env)
    if os.environ.get('SO_PIXEL') == '1' and os.path.isdir(pasta):
        r = None
    else:
      r = subprocess.run([sys.executable, os.path.join(AQUI, 'kit.py'), os.path.join(AQUI, 'modelos', modelo + '.py'), pasta],
                       env=e, capture_output=True, text=True)
    if r and (r.returncode or 'Traceback' in r.stderr + r.stdout):
        return nome + ' ERRO\n' + (r.stderr + r.stdout)[-1500:]
    r = subprocess.run([sys.executable, os.path.join(AQUI, 'pixel.py'), pasta, str(w), str(h),
                        os.path.join(AQUI, 'hd', nome + '.png')] + op, capture_output=True, text=True)
    return (r.stdout + r.stderr).strip()


if __name__ == '__main__':
    nomes = sys.argv[1:] or list(LISTA)
    with ThreadPoolExecutor(int(os.environ.get('JOBS', '3'))) as ex:
        for res in ex.map(fazer, nomes): print(res)
